= Omfang og avgrensing [[Omfang-og-avgresing]]

Standarden er anbefalt brukt for å beskrive datasett og datatjenester, samt kataloger med datasett og datatjenester. Den vil gjelde for alle datasett (inkludert åpne data) og datatjenester i offentlig sektor
__som beskrives med tanke på oppføring i en
katalog eller «inventarliste» (intern eller ekstern)__. Standarden er
ikke tenkt brukt for å beskrive fagsystem.

DCAT-AP-NO er en applikasjonsprofil og ikke en direkte oversettelse av EU sin https://semiceu.github.io/DCAT-AP/releases/3.0.0/[DCAT-AP &#x29C9;, window="_blank", role="ext-link"] og W3C sin https://www.w3.org/TR/vocab-dcat-3/[DCAT &#x29C9;, window="_blank", role="ext-link"]. I tillegg til å beskrive hvordan klasser og egenskaper i DCAT-AP og DCAT brukes, tilpasses også DCAT-AP  og DCAT til norske forhold ved å bruke norske utvidelser.

Istedenfor å ha alt spesifisert i denne standarden, er det etablert flere andre spesifikasjoner for å beskrive ulike aspekter ved datasett/datatjenester:

* *Kvalitetsbeskrivelser*: Det er etablert en https://data.norge.no/specification/dqv-ap-no/[norsk applikasjonsprofil av DQV (DQV-AP-NO) &#x29C9;, window="_blank", role="ext-link"] som spesifiserer hva skal/bør/kan tas med når datakvalitet beskrives. 

* *Informasjonsmodeller*: Det er etablert en norsk applikasjonsprofil av DCAT for beskrivelse og utveksling av informasjonsmodeller, https://data.norge.no/specification/modelldcat-ap-no/[ModellDCAT-AP-NO &#x29C9;, window="_blank", role="ext-link"]. I ModellDCAT-AP-NO er informasjonsmodell subklasse av `dct:Standard`. Ved å bruke egenskapen `dct:conformsTo` kan et datasett eller en datatjeneste referere til en informasjonsmodell.

* *Begrepsbeskrivelser*: Det er etablert en https://data.norge.no/specification/skos-ap-no-begrep[Forvaltningsstandard for begrepsbeskrivelser (SKOS-AP-NO-Begrep) &#x29C9;, window="_blank", role="ext-link"], som skal sikre at begrepene forvaltet av offentlig sektor, beskrives på en felles, strukturert måte. ved å bruke egenskapen `dct:subject` kan f.eks. et datasett referere til begreper som er viktige for å forstå datasettet. 
