= Omfang og avgrensing [[Omfang-og-avgresing]]

Standarden er anbefalt brukt for å beskrive datasett og datatjenester, samt kataloger med datasett og datatjenester. Den vil gjelde for alle datasett (inkludert åpne data) og datatjenester i offentlig sektor
__som beskrives med tanke på oppføring i en
katalog eller «inventarliste» (intern eller ekstern)__. Standarden er
ikke tenkt brukt for å beskrive dokumenter eller fagsystem.

DCAT-AP-NO er en applikasjonsprofil og ikke en direkte oversettelse av https://joinup.ec.europa.eu/collection/access-base-registries/solution/abr-specification-registry-registries/news/check-major-release-bregdcat-ap-v200[BRegDCAT-AP]. I tillegg til å beskrive hvordan klasser og egenskaper i BRegDCAT-AP brukes, tilpasses også BRegDCAT-AP til norske forhold ved å bruke norske utvidelser.

Istedenfor å ha alt spesifisert i denne standarden, er det utarbeidet flere andre spesifikasjoner for å beskrive ulike aspekter ved datasett/datatjenester:

* *Kvalitetsbeskrivelser*: Denne standarden bruker https://www.w3.org/TR/vocab-dqv/[DQV (Data Quality Vocabulary) fra W3C] til å beskrive kvalitet på datasett/datatjenester. Det er utarbeidet en https://data.norge.no/specification/dqv-ap-no/[norsk applikasjonsprofil av DQV (DQV-AP-NO)], som supplerer denne standarden med kvalitetsbeskrivelser.

* *Informasjonsmodeller*: Det er utabeidet en norsk applikasjonsprofil av DCAT for beskrivelse og utveksling av informasjonsmodeller, https://data.norge.no/specification/modelldcat-ap-no/[ModellDCAT-AP-NO]. I ModellDCAT-AP-NO er informasjonsmodell subklasse av `dct:Standard`. Ved å bruke egenskapen `dct:conformsTo` kan et datasett eller en datatjeneste referere til en informasjonsmodell.

* *Begrepsbeskrivelser*: Det er utarbeidet en https://data.norge.no/specification/forvaltningsstandard-begrepsbeskrivelser/[Forvaltningsstandard for begrepsbeskrivelser], som skal sikre at begrepene forvaltet av offentlig sektor, beskrives på en felles, strukturert måte. I denne sammenheng er den særlig relevant for begreper som er knyttet til datasett, datatjenester og informasjonsmodeller. 
