= Ord, uttrykk og forkortelser

Datasett::
Et _datasett_ er en samling med data (for eksempel i form av en tabell, liste eller en database) som kan gjøres tilgjengelig som en nedlastbar fil, og/eller nåes via et Web-API.

Datakatalog::
En _datakatalog_ gjør det mulig å finne opplysninger om datasett, hvem som forvalter dem og hvordan de eventuelt er gjort tilgjengelig for andre. Datakatalogen kan inneholde beskrivelser av alle virksomhetens datasett,  uavhengig av om de er distribuert som fil for nedlasting, gjennom et Web API eller om distribusjon ikke eksisterer.

Web API::
_Web Application Programming Interface_ gjør at dataprogrammer kan gjøre oppslag i et datasett ved hjelp av World Wide Web. For eksempel kan et datasett over bomstasjoner i Norge bli gjort tilgjengeleg for utviklere gjennom en web-API, slik at et dataprogram kan bruke kommunenummer for å hente en liste over alle bomstasjoner i en kommune.

Distribusjon::
En _distribusjon_  er en spesifikk måte å gjøre et datasettet tilgjengelig på. Hvert datasett kan være tilgjengelig på flere måter, for eksempel i ulike format eller fra ulike nettadresser. Eksempel på distribusjoner kan være nedlastbar CSV-fil, et API eller en RSS-strøm.

Åpne data::
Data som er fritt tilgjengelig for bruk av alle, både mennesker og maskiner. Dataforvaltere kan ikke kreve mer enn å bli oppgitt som kilde.

RDF::
_Resource Description Framework_. En gruppe W3C-spesifikasjoner som beskriver en modell for å representere metadata (data om data). Spesifikasjonene brukes i mange ulike sammenhenger for å beskrive informasjon og er et viktig element i visjonen om den semantiske webben.

DCAT::
_Data Catalog Vocabulary_. Et RDF-vokabular utviklet av W3C for å forenkle samhandling mellom datakataloger som er publisert på nettet.

DCAT-AP::
_DCAT Application profile for data portals in Europe_. En spesifikasjon basert på DCAT for å beskrive offentlige datasett i Europa

DCAT-AP-NO::
Kortnavnet på denne standarden ("Standard for beskrivelse av datakataloger og datasett").

JSON-LD::
_JavaScript Object Notation for Linked Data_. En JSON-basert serialisering av RDF. Anbefalt av W3C i januar 2014

URI::
_Uniform Resource Identifier_ en kompakt streng av tegn som identifiserer en abstrakt eller fysisk ressurs
