= Innledning

Dokumentet beskriver “Standard for beskrivelse av datasett og datakataloger (DCAT-AP-NO)” som skal sikre at beskrivelser av offentlige
data utføres på en felles, strukturert måte og i en maskinlesbar form. Standarden stiller krav til hva som _skal_, _bør_ og _kan_ være med i beskrivelsene, med spesifikasjon av dataformat.

Formålet med standarden er å legge tilrette for utveksling av beskrivelser av datasett, og å lette søk etter datasett. Standarden vil
gjelde datasett som forvaltes av offentlig sektor, og som beskrives med tanke på oppføring i en katalog eller «inventarliste». Standarden vil støtte søking i og deling av datasett på tvers av offentlig sektor (gjenbruk) og legge til rette for viderebruk i privat sektor. Standarden er således nyttig både for offentlig sektor selv og for næringsliv og sivilsamfunn for øvrig.

Ettersom standarden anbefaler formater som er beregnet for bruk i et Lenkede data-miljø, bør utgivere vurdere følgende anbefalinger fra W3C: http://www.w3.org/TR/swbp-vocab-pub/[Best Practice Recipes for Publishing RDF Vocabularies], http://www.w3.org/TR/ld-bp[Best Practices for Publishing Linked Data] og ISA-rapporten https://joinup.ec.europa.eu/community/semic/document/10-rules-persistent-uris[10 Rules for Persistent URIs]. Utgivere bør også vurdere å tildele URIer til alle forekomster av klassene som er beskrevet i standarden. Språk bør angis for alle literaler i tråd med http://www.loc.gov/standards/iso639-2/php/code_list.php[ISO 639].

DCAT-AP-NO er basert på den europeiske DCAT-profilen https://joinup.ec.europa.eu/asset/dcat_application_profile/description[DCAT
application profile for data portals in Europe] som er forvaltet av http://ec.europa.eu/isa/[EU-kommisjonens ISA-program].

Egenskapsnavnene fra den underliggende DCAT-AP er i denne standarden gitt norske navn.

NOTE: Siden standarden legger til rette for internasjonal utveksling, skal engelske egenskapsnavn i form av URIer benyttes.

== Avvik fra EUs DCAT-AP
Denne versjonen av standarden (DCAT-AP-NO versjon 1.1) avviker fra den underliggende link:https://joinup.ec.europa.eu/asset/dcat_application_profile/asset_release/dcat-ap-v11[DCAT-AP versjon 1.1] på følgende punkter:

. <<datasett-utgiver>> er endret fra anbefalt til obligatorisk egenskap.
. <<datasett-utgiver>> har endret beskrivelse: Anbefaling om bruk av autorativ URI eller organisasjonsnummer er lagt til i beskrivelsen.
. <<datasett-tema>> er endret fra anbefalt til obligatorisk egenskap.
. <<datasett-tema>> har endret beskrivelse: http://psi.norge.no/los/struktur.html[LOS] lagt til som anbefalt vokabular
. <<datasett-identifikator>> er endret fra valgfri til obligatorisk egenskap
. <<datasett-identifikator>> er endret fra å være unik i kontekst av katalogen til en globalt unik identifikator
. for egenskapen <<datasett-dekningsomrade>> er anbefalingen om bruk av vokabularene link:http://publications.europa.eu/mdr/authority/continent/[MDR Continents Named Authority List] link:http://publications.europa.eu/mdr/authority/country/[MDR Countries Named Authority List] og link:http://publications.europa.eu/mdr/authority/place/[MDR Places Named Authority List] fjernet. Bruk av link:http://sws.geonames.org/[Geonames] er endret til påkrevd
. <<datasett-tilgangsniva>> er endret fra valgfri til anbefalt egenskap
. <<datasett-skjermingshjemmel>> er lagt til som ny anbefalt egenskap
. <<datasett-begrep>> er lagt til som ny anbefalt egenskap
. <<datasett-skaper>> (opphavsorganisasjon) er lagt til som ny valgfri egenskap
. relasjonene <<datasett-er-del-av>> og <<datasett-har-del>> er lagt til som nye valgfrie egenskaper
. relasjonene <<datasett-krever>> og <<datasett-er-pakrevd-av>> er lagt til som nye valgfrie egenskaper
. relasjonene <<datasett-erstatter>> og <<datasett-erstattes-av>> er lagt til som nye valgfrie egenskaper
. relasjonene <<datasett-refererer-til>> og <<datasett-er-referert-av>> er lagt til som nye valgfrie egenskaper
. <<distribusjon-format>> er endret fra anbefalt til obligatorisk.
. <<distribusjon-format>> er endret til å tillate flere verdier (kardinaliteten er endret fra 0..1 til 1..n)
. <<distribusjon-format>> har endret beskrivelse: IANA Media Types skal brukes. Formater som ikke er på IANA-listen legges til etter samme struktur.
. egenskapen *mediatype* er fjernet fordi egenskapen <<distribusjon-format>> er vurdert til å dekke behovet
. JSON-LD er lagt til som anbefalt publiseringsformat i tillegg til RDF/XML
. Egenskapene er gitt norske navn (URIer skal brukes -  ikke navnet på egenskapene)
