= Innledning

Dokumentet beskriver “Standard for beskrivelse av datasett og
datakataloger (DCAT-AP-NO)” som skal sikre at beskrivelser av offentlige
data utføres på en felles, strukturert måte og i en maskinlesbar form.
Standarden stiller krav til hva som _skal_, _bør_ og _kan_ være med i
beskrivelsene, med spesifikasjon av dataformat.

Formålet med standarden er å legge tilrette for utveksling av
beskrivelser av datasett, og å lette søk etter datasett. Standarden vil
gjelde datasett som forvaltes av offentlig sektor, og som beskrives med
tanke på oppføring i en katalog eller «inventarliste». Standarden vil
støtte søking i og deling av datasett på tvers av offentlig sektor
(gjenbruk) og legge til rette for viderebruk i privat sektor. Standarden
er således nyttig både for offentlig sektor selv og for næringsliv og
sivilsamfunn for øvrig.

Arbeidet med informasjonsforvaltning i offentlig sektor har vist at det
er behov for beskrivelser av alle datasett i forvaltningen, og det vil
være hensiktsmessig at disse datasettene beskrives på en helhetlig måte.
Standarden vil således være nyttig for etatens forvaltning av egen
informasjon, og for andre etater, næringsliv og sivilsamfunn som har
behov for å vite hvilke data etaten forvalter. DCAT-AP-NO skal derfor
brukes i beskrivelsen av både åpne og ikke-åpne data selv om DCAT-AP
primært er utviklet for åpne data.

Ettersom standarden anbefaler formater som er beregnet for bruk i et
Lenkede data-miljø, bør utgivere vurdere anbefalingene i W3C Notes
http://www.w3.org/TR/swbp-vocab-pub/[Best Practice Recipes for
Publishing RDF Vocabularies], http://www.w3.org/TR/ld-bp[Best Practices
for Publishing Linked Data] og ISA-rapporten
https://joinup.ec.europa.eu/community/semic/document/10-rules-persistent-uris[10
Rules for Persistent URIs]. Utgivere bør også vurdere å tildele URIer
til alle forekomster av klassene som er beskrevet i standarden. Språk
bør angis for alle literaler i tråd med
http://www.loc.gov/standards/iso639-2/php/code_list.php[ISO 639].

DCAT-AP-NO er basert på den europeiske DCAT-profilen
https://joinup.ec.europa.eu/asset/dcat_application_profile/description[DCAT
application profile for data portals in Europe] som er forvaltet av
http://ec.europa.eu/isa/[EU-kommisjonens ISA-program]. Siden
standarden legger til rette for internasjonal utveksling, skal engelske
egenskapsnavn i form av URIer benyttes.

Egenskapsnavnene fra den underliggende DCAT-AP er i «Norsk
standard for beskrivelse av datasett og datakataloger» gitt norske navn.

== Avvik fra den europeiske DCAT-AP v1.1
Denne versjonen av standarden (DCAT-AP-NO versjon 1.1) avviker fra den underliggende DCAT-AP versjon 1.1 på følgende punkter:

=== For klassen Datasett:
* link:#datasett-tilgangsniva[tilgangsnivå] er endret fra valgfri til anbefalt egenskap
* link:#datasett-skjermingshjemmel[skjermingshjemmel] er lagt til som ny anbefalt egenskap
* link:#datasett-begrep[begrep] er lagt til som ny anbefalt egenskap
* link:#datasett-identifikator[identifikator] er endret fra valgfri til obligatorisk egenskap 
* link:#datasett-identifikator[identifikator] endret fra å være unik i kontekst av katalogen til en globalt unik identifikator
* link:#datasett-tema[tema] er endret fra anbefalt til obligatorisk og http://psi.norge.no/los/struktur.html[LOS] er er lagt til som anbefalt vokabular
* link:#datasett-skaper[skaper] er lagt til som valgfri egenskap
* relasjonene link:#datasett-er-del-av[er del av]/ link:#datasett-har-del[har del] er lagt til som ny egenskaper
* relasjonene link:#datasett-krever[krever] / link:#datasett-er-pakrevd-av[er påkrevd av] er lagt til som nye egenskaper
* relasjonene link:#datasett-erstatter[erstatter] / link:#datasett-erstattes-av[erstattes av] er lagt til som nye egenskaper
* relasjonene link:#datasett-refererer-til[refererer til] / link:datasett-er-referert-av[er referert av] er lagt til som nye egenskaper

=== For klassen Distribusjon:
* egenskapen *mediatype* er fjernet fordi egenskapen link:#distribusjon-format[format] dekker behovet
* for egenskapen link:#distribusjon-format[format] er kardinaliteten endret fra 0..1 til 1..n 

=== Andre endringer: 
* JSON-LD er lagt til som anbefalt publiseringsformat i tillegg til
RDF/XML
* Egenskapene er gitt norske navn (URIer skal brukes -  ikke navnet på
egenskapene)
