= Vedlegg B - Oversikt over norske utvidelser [[Oversikt-norske-utvidelser]]

// kommentar: dette er ren klipp-og-lim fra kapitlene for å gjenta norske utvidelser i en samlet oversikt

«Norsk utvidelse» i konteksten av denne standarden betyr avvik mellom DCAT-AP-NO og summen av EU sin DCAT-AP og W3C sin DCAT. EU har valgt å ikke gjenta egenskaper fra DCAT i DCAT-AP når det ikke er foretatt endringer/tilpasninger, hvilket betyr at nasjonale applikasjonsprofiler kan bruke egenskaper fra DCAT uten å bryte med DCAT-AP. For å øke leservennlighet har vi i DCAT-AP-NO valgt å gjenta egenskaper fra DCAT-AP og DCAT som vi trenger for å dekke norske behov. Der det ikke står «norsk utvidelse» betyr at egenskapen er brukt slik den er spesifisert i enten DCAT-AP eller DCAT. Der det står «norsk utvidelse», er kravet til egenskapen endret (f.eks. med forklaringen noe a la "Kravnivået er endret fra valgfri til anbefalt"), eller at egenskapen ikke er å finne i hverken DCAT-AP eller DCAT (f.eks. med forklaring "Ikke eksplisitt spesifisert i DCAT-AP/DCAT").

Inntil eventuell uoverensstemmelse mellom listen nedenfor og merknadene de aktuelle egenskapene der det står (ev. mangler) «norsk utvidelse» blir rettet opp, har merknadene forrang.

Tabellen nedenfor er sortert i samme rekkefølge som klassene/egenskapene er spesifisert i <<Spesifikasjon-per-klasse>>. 

[cols="20,20,60"]
|===
|*Egenskaps-/klassenavn / _Norwegian name_* |*Egenskaps-/klasseURI / _Property/class URI_*| *Norsk utvidelse / _Norwegian extension_* 
| Aktør – organisasjonsidentifikator | dct:identifier |  
Ikke eksplisitt spesifisert i DCAT-AP/DCAT. 

 _Not explicitly specified in DCAT-AP/DCAT._
| Datasett – kontaktpunkt | dcat:contactPoint |
Kravnivået er endret til fra anbefalt til obligatorisk, og dermed også multiplisitet til 1..n. 

_The requirement level is changed from recommended to mandatory, thus also the multiplicity to 1..n._
| Datasett – tema | dcat:theme |
Kravnivå er endret til fra anbefalt til obligatorisk, og dermed også multiplisitet til 1..n.

__The requirement level is changed from recommended to mandatory, thus also the multiplicity to 1..n.__
| Datasett – tema | dcat:theme |
https://psi.norge.no/los/struktur.html[Los &#x29C9;, window="_blank", role="ext-link"] BØR brukes i tillegg. 

__https://psi.norge.no/los/struktur.html[Los &#x29C9;, window="_blank", role="ext-link"] SHOULD be used in addition.__
| Datasett – utgiver | dct:publisher |
Kravnivået er endret fra anbefalt til obligatorisk, dermed også multiplisitet fra 0..1 til 1..1.

__The requirement level is changed from recommended to mandatory, thus also the multiplicity from 0..1 to 1..1.__
| Datasett – begrep | dct:subject |
Ikke eksplisitt spesifisert i DCAT-AP/DCAT.

__Not explicitly specified in DCAT-AP/DCAT.__
| Datasett – ble generert ved | prov:wasGeneratedBy |
Kravnivået er endret fra valgfri til anbefalt.

__The requirement level is changed from optional to recommended.__
| Datasett – ble generert ved | prov:wasGeneratedBy |
Verdien BØR velges fra kontrollert vokabular https://data.norge.no/vocabulary/provenance-activity-type[Proveniensaktivitetstype &#x29C9;, window="_blank", role="ext-link"].

__The value SHOULD be chosen from the controlled vocabulary https://data.norge.no/vocabulary/provenance-activity-type[Provenance activity type &#x29C9;, window="_blank", role="ext-link"].__
| Datasett – dekningsområde | dct:spatial | 
For å angi dekningsområde i Norge, BØR Kartverkets kontrollerte vokabular https://data.geonorge.no/administrativeEnheter/nasjon/doc/173163[Administrative enheter &#x29C9;, window="_blank", role="ext-link"] brukes i tillegg.

__To specify spatial coverage in Norway, the Norwegian Mapping Authority’s controlled vocabulary https://sws.geonames.org/[Administrative units &#x29C9;, window="_blank", role="ext-link"] SHOULD be used in addition.__
| Datasett – gjeldende lovgivning | dcatap:applicableLegislation |
Kravnivået endret fra valgfri til anbefalt.

__The requirement level changed from optional to recommended.__
| Datasett – tilgangsrettigheter | dct:accessRights |
Kravnivået er endret fra valgfri til anbefalt.

__The requirement level is changed from optional to recommended.__
| Datasett – endringsdato | dct:modified |
Verdiområdet er eksplisitt spesifisert som `xsd:date or xsd:dateTime`, istedenfor å referere til den generiske datatype Temporal literal.

__The range is explicitly specified as `xsd:date or xsd:dateTime`, instead of referring to the generic datatype Temporal Literal.__
| Datasett – har del | dct:hasPart |
Ikke eksplisitt spesifisert i DCAT-AP/DCAT. 

__Not explicitly specified in DCAT-AP/DCAT.__
| Datasett – har gebyr | cv:hasCost | 
Ikke eksplisitt spesifisert i DCAT-AP/DCAT. 

__Not explicitly specified in DCAT-AP/DCAT.__
| Datasett – utgivelsesdato | dct:issued | 
Verdiområdet er eksplisitt spesifisert som `xsd:date or xsd:dateTime`, istedenfor å referere til den generiske datatype Temporal literal.

__The range is explicitly specified as `xsd:date or xsd:dateTime`, instead of referring to the generic datatype Temporal Literal.__
| Datasettserie – kontaktpunkt | dcat:contactPoint |
Kravnivået er endret til fra anbefalt til obligatorisk, og dermed også multiplisitet til 1..n.

__The requirement level is changed from recommended to mandatory, thus also the multiplicity to 1..n.__
| Datasettserie – tema | dcat:theme | 
Kravnivået er endret til fra anbefalt til obligatorisk, og dermed også multiplisitet til 1..n.

__The requirement level is changed from recommended to mandatory, thus also the multiplicity to 1..n.__
| Datasettserie – tema | dcat:theme | 
https://psi.norge.no/los/struktur.html[Los &#x29C9;, window="_blank", role="ext-link"] BØR brukes i tillegg. 

__https://psi.norge.no/los/struktur.html[Los &#x29C9;, window="_blank", role="ext-link"] SHOULD be used in addition.__
| Datasettserie – utgiver | dct:publisher |
Kravnivået endret fra anbefalt til obligatorisk, dermed også multiplisitet fra 0..1 til 1..1.

__The requirement level changed from recommended to mandatory, thus also the multiplicity from 0..1 to 1..1.__
| Datasettserie – dekningsområde | dct:spatial | 
For å angi dekningsområde i Norge, BØR Kartverkets kontrollerte vokabular https://data.geonorge.no/administrativeEnheter/nasjon/doc/173163[Administrative enheter &#x29C9;, window="_blank", role="ext-link"] brukes i tillegg.

__To specify spatial coverage in Norway, the Norwegian Mapping Authority’s controlled vocabulary https://sws.geonames.org/[Administrative units &#x29C9;, window="_blank", role="ext-link"] SHOULD be used in addition.__
| Datasettserie – første | dcat:first | 
Kravnivået endret fra valgfri til anbefalt.

__The requirement level changed from optional to recommended.__
| Datasettserie – gjeldende lovgivning | dcatap:applicableLegislation |
Kravnivået endret fra valgfri til anbefalt.

__The requirement level changed from optional to recommended.__
| Datasettserie – siste | dcat:last |
Kravnivået endret fra valgfri til anbefalt.

__The requirement level changed from optional to recommended.__
| Datasettserie – tidsrom | dct:temporal | 
Kravnivået endret fra valgfri til anbefalt.

__The requirement level changed from optional to recommended.__
| Datasettserie – endringsdato | dct:modified |
Verdiområdet er eksplisitt spesifisert som `xsd:date or xsd:dateTime`, istedenfor å referere til den generiske datatype Temporal literal.

__The range is explicitly specified as `xsd:date or xsd:dateTime`, instead of referring to the generic datatype Temporal Literal.__
| Datasettserie – utgivelsesdato | dct:issued |
Verdiområdet er eksplisitt spesifisert som `xsd:date or xsd:dateTime`, istedenfor å referere til den generiske datatype Temporal literal.

__The range is explicitly specified as `xsd:date or xsd:dateTime`, instead of referring to the generic datatype Temporal Literal.__
| Datatjeneste – endepunktsURL | dcat:endpointURL |
Multiplisiteten endret fra 1..n til 1..1, fordi Datatjeneste med flere ulike endepunktsURLer bør betraktes som flere ulike datatjenester.

__The multiplicity is changed from 1..n to 1..1.__
| Datatjeneste – kontaktpunkt | dcat:contactPoint |
Kravnivået er endret til fra anbefalt til obligatorisk, og dermed også multiplisitet til 1..n.

__The requirement level is changed from recommended to mandatory, thus also the multiplicity to 1..n.__
| Datatjeneste – utgiver | dct:publisher |
Kravnivået endret fra anbefalt til obligatorisk og dermed også multiplisiteten fra 0..1 til 1..1. 

__The requirement level changed from recommended to mandatory and thus also the multiplicity from 0..1 to 1..1.__
| Datatjeneste – format | dct:format |
Kravnivå endret fra valgfri til anbefalt.

__The requirement level changed from optional to recommended.__
| Datatjeneste – gjeldende lovgivning | dcatap:applicableLegislation |
Kravnivået endret fra valgfri til anbefalt.

__The requirement level changed from optional to recommended.__
| Datatjeneste – tema | dcat:theme |
https://psi.norge.no/los/struktur.html[Los &#x29C9;, window="_blank", role="ext-link"] BØR brukes i tillegg. 

__https://psi.norge.no/los/struktur.html[Los &#x29C9;, window="_blank", role="ext-link"] SHOULD be used in addition.__
| Datatjeneste – lisens | dct:license |
Verdien SKAL velges fra EUs kontrollerte vokabular https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/licence[__Licence__ &#x29C9;, window="_blank", role="ext-link"].

__The value MUST be chosen from EU's controlled vocabulary https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/licence[Licence &#x29C9;, window="_blank", role="ext-link"]__
| Datatjeneste – medietype | dcat:mediaType |
Ikke eksplisitt spesifisert i DCAT-AP/DCAT.

__Not explicitly specified in DCAT-AP/DCAT.__
| Datatjeneste – type | dct:type |
Multiplisiteten endret fra 0..n til 0..1.

__The multiplicity changed from 0..n to 0..1.__
| Distribusjon – lisens | dct:license| 
Verdien SKAL velges fra EUs kontrollerte vokabular https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/licence[__Licence__ &#x29C9;, window="_blank", role="ext-link"].

__The value MUST be chosen from EU's controlled vocabulary https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/licence[Licence &#x29C9;, window="_blank", role="ext-link"].__
| Distribusjon – status | adms:status |
Kravnivå endret fra valgfri til anbefalt, fordi status på distribusjon er viktig å vite når man skal vurdere om en distribusjon skal/kan brukes.

__The requirement level changed from optional to recommended.__
| Distribusjon – status | adms:status |
Verdien SKAL velges fra EU's kontrollerte vokabular https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/distribution-status[__Distribution status__ &#x29C9;, window="_blank", role="ext-link"].

__The value MUST be chosen from EU's controlled vocabulary https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/distribution-status[Distribution status &#x29C9;, window="_blank", role="ext-link"].__
| Distribusjon – endringsdato | dct:modified |
Verdiområdet er eksplisitt spesifisert som `xsd:date or xsd:dateTime`, istedenfor å referere til den generiske datatype Temporal literal.

__The range is explicitly specified as `xsd:date or xsd:dateTime`, instead of referring to the generic datatype Temporal Literal.__
| Distribusjon – komprimeringsformat | dcat:compressFormat | 
Verdien BØR være en medietype fra det offisielle registeret av https://www.iana.org/assignments/media-types/media-types.xhtml[medietyper forvaltet av IANA &#x29C9;, window="_blank", role="ext-link"].

__It SHOULD be expressed using a media type as defined in the official register of https://www.iana.org/assignments/media-types/media-types.xhtml[media types managed by IANA &#x29C9;, window="_blank", role="ext-link"].__
| Distribusjon – pakkeformat | dcat:packageFormat | 
Verdien BØR være en medietype fra det offisielle registeret av https://www.iana.org/assignments/media-types/media-types.xhtml[medietyper forvaltet av IANA &#x29C9;, window="_blank", role="ext-link"].

__It SHOULD be expressed using a media type as defined in the official register of https://www.iana.org/assignments/media-types/media-types.xhtml[media types managed by IANA &#x29C9;, window="_blank", role="ext-link"].__
| Distribusjon – utgivelsesdato | dct:issued |
Verdiområdet er eksplisitt spesifisert som `xsd:date or xsd:dateTime`, istedenfor å referere til den generiske datatype Temporal literal.

__The range is explicitly specified as `xsd:date or xsd:dateTime`, instead of referring to the generic datatype Temporal Literal.__
| Gebyr | cv:Cost | 
Hele klassen: Ikke eksplisitt spesifisert i DCAT-AP/DCAT.

__The whole class: Not explicitly specified in DCAT-AP/DCAT.__
| Katalog – kontaktpunkt | dcat:contactPoint |
Kravnivået endret fra valgfri (i DCAT) til obligatorisk, dermed også multiplisitet fra 0..1 til 1..1.

__The requirement level changed from optional (in DCAT) to mandatory, thus also the multiplicity from 0..1 to 1..1.__
| Katalog – dekningsområde | dct:spatial | 
Norsk utvidelse: For å angi dekningsområde i Norge, BØR Kartverkets kontrollerte vokabular https://data.geonorge.no/administrativeEnheter/nasjon/doc/173163[Administrative enheter &#x29C9;, window="_blank", role="ext-link"] brukes i tillegg.

__To specify spatial coverage in Norway, the Norwegian Mapping Authority’s controlled vocabulary https://sws.geonames.org/[Administrative units &#x29C9;, window="_blank", role="ext-link"] SHOULD be used in addition.__
| Katalog – endringsdato | dct:modified |
Verdiområdet er eksplisitt spesifisert som `xsd:date or xsd:dateTime`, istedenfor å referere til den generiske datatype Temporal literal. 

__The range is explicitly specified as `xsd:date or xsd:dateTime`, instead of referring to the generic datatype Temporal Literal.__
| Katalog – lisens | dct:license |
Verdien SKAL velges fra EUs kontrollerte vokabular https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/licence[__Licence__ &#x29C9;, window="_blank", role="ext-link"].

__The value MUST be chosen from EU's controlled vocabulary https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/licence[Licence &#x29C9;, window="_blank", role="ext-link"].__
| Katalog – temaer | dcat:themeTaxonomy |
https://psi.norge.no/los/struktur.html[Los &#x29C9;, window="_blank", role="ext-link"] BØR brukes. 

__https://psi.norge.no/los/struktur.html[Los &#x29C9;, window="_blank", role="ext-link"] SHOULD be used.__
| Katalog – utgivelsesdato | dct:issued |
Verdiområdet er eksplisitt spesifisert som `xsd:date or xsd:dateTime`, istedenfor å referere til den generiske datatype Temporal literal. 

__The range is explicitly specified as `xsd:date or xsd:dateTime`, instead of referring to the generic datatype Temporal Literal.__
| Katalogpost – endringsdato | dct:modified |
Verdiområdet er eksplisitt spesifisert som `xsd:date or xsd:dateTime`, istedenfor å referere til den generiske datatype Temporal literal.

__The range is explicitly specified as `xsd:date or xsd:dateTime`, instead of referring to the generic datatype Temporal Literal.__
| Katalogpost – status | adms:status |
Verdien SKAL velges fra EU's kontrollerte vokabular https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/distribution-status[__Distribution status__ &#x29C9;, window="_blank", role="ext-link"].

__The value MUST be chosen from EU's controlled vocabulary https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/distribution-status[Distribution status &#x29C9;, window="_blank", role="ext-link"].__
| Katalogpost – utgivelsesdato | dct:issued |
Verdiområdet er eksplisitt spesifisert som `xsd:date or xsd:dateTime`, istedenfor å referere til den generiske datatype Temporal literal.

__The range is explicitly specified as `xsd:date or xsd:dateTime`, instead of referring to the generic datatype Temporal Literal.__
| Kontaktopplysning   | vcard:Kind | 
Alle egenskaper i klasse: Ikke eksplisitt spesifisert i DCAT-AP/DCAT. 

__All properties in the class: Not explicitly specified in DCAT-AP/DCAT.__
| Regulativ ressurs | eli:LegalResource |
Alle egenskaper i klassen: Ikke eksplisitt spesifisert DCAT-AP/DCAT.

__All properties in the class: Not explicitly specified in DCAT-AP/DCAT.__
| Rettighetsuttalelse | odrs:RightsStatement | 
Hele klassen: Ikke eksplisitt spesifisert DCAT-AP/DCAT. `odrs:RightsStatement` er imidlertid en subklasse av `dct:RightsStatement` brukt i DCAT-AP. 

__The whole class: Not explicitly specified in DCAT-AP/DCAT. `odrs:RightsStatement` is though a subclass of `dct:RightsStatement` used in DCAT-AP._
| Standard | dct:Standard |
Alle egenskaper i klassen: Ikke eksplisitt spesifisert DCAT-AP/DCAT.

__All properties in the class: Not explicitly specified in DCAT-AP/DCAT.__
| Tidsrom – sluttdato/tid | dcat:endDate |
Verdiområdet er eksplisitt spesifisert som `xsd:date or xsd:dateTime`, istedenfor å referere til den generiske datatype Temporal literal.

__The range is explicitly specified as `xsd:date or xsd:dateTime`, instead of referring to the generic datatype Temporal Literal.__
| Tidsrom – startdato/tid | dcat:startDate |
Verdiområdet er eksplisitt spesifisert som `xsd:date or xsd:dateTime`, istedenfor å referere til den generiske datatype Temporal literal.

__The range is explicitly specified as `xsd:date or xsd:dateTime`, instead of referring to the generic datatype Temporal Literal.__
|===

