= Vedlegg C - Endringslogg [[Endringslogg]]

Mindre redaksjonelle justeringer av tekster (f.eks. egenskapsnavn, egenskapsbeskrivelser, lenker osv.) beskrives ikke her.

== Endringer av dokumentstrukturen fra versjon 2.2 til denne versjonen 

:xrefstyle: short

Standarden inneholder nå tre hoveddeler i tillegg til det innledende kapittelet og vedleggene:

* <<Forenklet-fremstilling>>  inneholder en forenklet fremstilling av de viktigste kravene i standarden. Denne delen er ment for den ikke-tekniske målgruppen. 

* <<Spesifikasjon-per-klasse>>  inneholder tekniske krav til hvordan beskrivelser av datasett, datatjenester osv. skal representeres i RDF. Denne delen er ment for den tekniske målgruppen.  
** Hver klasse og dens egenskaper er samlet i samme kapittel, istedenfor to separate kapitler i forrige versjon.
** Krav til bruk av kontrollerte vokabularer er nå tatt med som merknader til de aktuelle egenskapene, istedenfor i eget kapittel i forrige versjon. 
** Eventuelle norske utvidelser sammenlignet med DCAT-AP og DCAT, er dokumentert sammen med spesifikasjonen av den aktuelle klassen/egenskapen, i tillegg til en samlet oversikt i <<Oversikt-norske-utvidelser>>. 

** Tabeller som brukes til å spesifisere klasser og egenskaper er endret:

*** Tabellene har fått nye ledetekster.
*** Det er nå også tatt med engelsk tekst, primært ment for engelsktalende utviklere av verktøystøtte. 

* <<Spesielle-temaer>> inneholder forklaring/veiledning til hvordan DCAT-AP-NO er tenkt brukt i noen spesifikke brukstilfeller. Denne delen er ment for både den ikke-tekniske og den tekniske målgruppen, fortrinnsvis sammen. Denne delen sammen med eksemplene gitt i standarden, skal (over tid) erstatte en separat veileder for hvordan standarden er tenkt brukt. 

:xrefstyle: full

== Endringer av klasser og egenskaper fra versjon 2.2 til denne versjonen

EU har begynt å ikke gjenta valgfrie egenskaper fra W3Cs DCAT med mindre EU gjør tilpasninger, men presiserer samtidig at nasjonale applikasjonsprofiler kan bruke egenskaper fra DCAT uten å bryte med DCAT-AP. Denne versjonen av DCAT-AP-NO er derfor basert på summen av DCAT-AP og DCAT (istedenfor BRegDCAT-AP som den gang inneholdt hele DCAT-AP med utvidelser). 

Denne versjonen spesifiserer _ikke_ kravnivå (obligatorisk/anbefalt/valgfri) for klassene, se imidlertid <<Samsvarskrav>> for hva applikasjonene skal kunne håndtere. Dette i henhold til EUs DCAT-AP. 

Vi følger DCAT-AP som følger DCAT når det gjelder inverse egenskaper, at inverse egenskaper ikke tas med i standarden. Alle inverse egenskaper er derfor utgått fra denne versjonen av DCAT-AP-NO. Man __kan__ bruke en invers egenskap, _i tillegg til_ og _ikke istedenfor_ egenskapen som er eksplisitt tatt med i standarden. Se <<Om-inverse-egenskaper>>.

Oversikt over *nye klasser*, dvs. enten helt nye eller nå i denne versjonen eksplisitt spesifisert med egenskaper: 

* <<Gebyr>>, for å kunne beskrive ev. kostnader knyttet til bruk av et datasett, med standardiserte egenskaper.
* <<Kontaktopplysning>>, for å kunne beskrive et kontaktpunkt, med standardiserte egenskaper
* <<Rettighetserklæring>>, for å kunne beskrive ev. rettigheter knyttet til et datasett, med standardiserte egenskaper

Oversikt over *utgåtte klasser*, dvs. klasser som i denne versjonen ikke lenger er eksplisitt spesifisert med egenskaper: 

* Lisensdokument (dct:LicenseDocument): Det ikke er behov for å lage egne instanser av denne klasse fordi egenskapene som bruke denne klassen som range skal referere til kontrollerte vokabularer.
* Lokasjon (dct:Location): Det ikke er behov for å lage egne instanser av denne klasse fordi egenskapene som bruke denne klassen som range skal referere til kontrollerte vokabularer.
* Offentlig organisasjon (cv:PublicOrganisation): Behovet er dekket av https://data.norge.no/specification/cpsv-ap-no[CPSV-AP-NO &#x29C9;, window="_blank", role="ext-link"]. 
* Offentlig tjeneste (cpsv:PublicService): Behovet er dekket av https://data.norge.no/specification/cpsv-ap-no[CPSV-AP-NO &#x29C9;, window="_blank", role="ext-link"].
* Regel (cpsv:Rule): Behovet er dekket av https://data.norge.no/specification/cpsv-ap-no[CPSV-AP-NO &#x29C9;, window="_blank", role="ext-link"].
* Tema (skos:Concept): Det ikke er behov for å lage egne instanser av denne klasse fordi egenskapene som bruke denne klassen som range skal referere til kontrollerte vokabularer.
* Tematisk skjema (skos:ConceptScheme): Det ikke er behov for å lage egne instanser av denne klasse fordi egenskapene som bruke denne klassen som range skal referere til kontrollerte vokabularer.

Oversikt over *endrede krav i eksisterende klasser*: 

* <<Datasett>>: 
** Nye egenskaper:
*** __#kommer#__ 
** Utgåtte egenskaper: 
*** _#kommer#_
** Endrede kravnivå og/eller multiplisitet: 
*** kontaktpunkt (dcat:contactPoint) er endret fra anbefalt til obligatorisk og dermed også multiplisiteten fra 0..n til 1..n. Dette for å kunne ta kontakt med den ansvarlige.
** Endrede krav til bruk av kontrollerte vokabularer: 
*** _#kommer#_

* <<Datasettserie>>: 
** Nye egenskaper:
*** __#kommer#__ 
** Utgåtte egenskaper: 
*** _#kommer#_
** Endrede kravnivå og/eller multiplisitet: 
*** _#kommer#_
** Endrede krav til bruk av kontrollerte vokabularer: 
*** _#kommer#_

* <<Datatjeneste>>: 
** Nye egenskaper:
*** __#kommer#__ 
** Utgåtte egenskaper: 
*** _#kommer#_
** Endrede kravnivå og/eller multiplisitet: 
*** _#kommer#_
** Endrede krav til bruk av kontrollerte vokabularer: 
*** _#kommer#_

* <<Distribusjon>>: 
** Nye egenskaper:
*** __#kommer#__ 
** Utgåtte egenskaper: 
*** _#kommer#_
** Endrede kravnivå og/eller multiplisitet: 
*** _#kommer#_
** Endrede krav til bruk av kontrollerte vokabularer: 
*** _#kommer#_

* <<Katalog>>: 
** Nye egenskaper:
*** __#kommer#__ 
** Utgåtte egenskaper: 
*** _#kommer#_
** Endrede kravnivå og/eller multiplisitet: 
*** _#kommer#_
** Endrede krav til bruk av kontrollerte vokabularer: 
*** _#kommer#_

* <<Katalogpost>>: 
** Nye egenskaper:
*** __#kommer#__ 
** Utgåtte egenskaper: 
*** _#kommer#_
** Endrede kravnivå og/eller multiplisitet: 
*** _#kommer#_
** Endrede krav til bruk av kontrollerte vokabularer: 
*** _#kommer#_

* <<RegulativRessurs>>: 
** Nye egenskaper:
*** __#kommer#__ 
** Utgåtte egenskaper: 
*** _#kommer#_
** Endrede kravnivå og/eller multiplisitet: 
*** _#kommer#_
** Endrede krav til bruk av kontrollerte vokabularer: 
*** _#kommer#_

* <<Sjekksum>>: 
** Nye egenskaper:
*** __#kommer#__ 
** Utgåtte egenskaper: 
*** _#kommer#_
** Endrede kravnivå og/eller multiplisitet: 
*** _#kommer#_
** Endrede krav til bruk av kontrollerte vokabularer: 
*** _#kommer#_

* <<Standard>> 
** Nye egenskaper:
*** __#kommer#__ 
** Utgåtte egenskaper: 
*** _#kommer#_
** Endrede kravnivå og/eller multiplisitet: 
*** _#kommer#_
** Endrede krav til bruk av kontrollerte vokabularer: 
*** _#kommer#_
