== Datakatalog

=== Hva er en datakatalog?

Datasett fra en virksomhet eller flere virksomheter samles i en datakatalog.

=== Tittel

.Sammendrag

Kortfattet om katalogen. Angi, uten å liste, hvilke datasett den omfatter.

.Anbefalinger

Kortfattet om katalogen

 * Angi, uten å liste, hvilke datasett den omfatter,
 * f.eks. datasettene til Brønnøysundregistrene.

.Eksempler

----
<> <http://brreg.no/catalogs/974760673>
    	a dcat:Catalog ;
    	dct:title "Datakatalog for REGISTERENHETEN I BRØNNØYSUND"@nb ;
----

=== Beskrivelse av katalog

.Sammendrag

En kort og presis beskrivelse av datasettet skal gjøre det lett for andre å se hva det inneholder. Beskrivelse er et obligatorisk felt.

.Anbefalinger

En kort og presis beskrivelse av datasettet skal gjøre det lett for andre å se hva det inneholder. Beskrivelse er et obligatorisk felt.

.Eksempler
----
<> <http://brreg.no/catalogs/974760673>
    	a          	dcat:Catalog ;
    	dct:description "Katalog over alle data i Brønnøysundregistrene"@nb ;
----

=== Datasett

.Sammendrag
Beskriver datasettene i katalogen. Minst ett datasett er påkrevd.

.Anbefalinger
Beskriver datasettene i katalogen. Minst ett datasett er påkrevd.

 * Lenke til alle datasettene

.Eksempler
----
<> <http://brreg.no/catalogs/974760673>
    	 dcat:dataset   <http://brreg.no/catalogs/974760673/datasets/b97e7db3-8e46-4bc4-857e-77d7280b0e9e> , <http://brreg.no/catalogs/974760673/datasets/1ffcb9e4-008b-4333-a372-268f50d01482> , <http://brreg.no/catalogs/974760673/datasets/9922b7df-4fb8-4e1e-8da9-85736e37195f> .
----

=== Eier av katalog

.Sammendrag
Identifisering av den enheten som er ansvarlig for katalogen

.Anbefalinger
Identifisering av den enheten som er ansvarlig for katalogen. Eier er et obligatorisk felt.

 * Skal peke på en Enhet (juridisk person, organisasjonsledd, underenhet)
 * Det offisielle navnet på virksomheten vil hentes fra Enhetsregisteret, men kortform (f.eks. Difi) kan legges inn av brukeren

.Eksempler
* [*] Brønnøysundregistrene
----
<> <http://brreg.no/catalogs/974760673>
     dct:publisher <http://data.brreg.no/enhetsregisteret/enhet/974760673> .
# brreg

----

=== Utgivelse

.Sammendrag
Dato/tid katalogen først ble publisert.

.Anbefalinger
Dato/tid katalogen først ble publisert.

.Eksempler

* [*] 01.01.2017 00:00

----
<> <http://brreg.no/catalogs/974760673>
     dct:issued “2017-01-01T00:00:00+01:00”^xsd:DateTime .
----


=== Sist oppdatert

.Sammendrag
Dato/tid sist katalogen ble endret,. Dette kan være endring av en datasettbeskrivelse, eller andre metadata i katalogen.

.Anbefalinger
Dato/tid sist katalogen ble endret,. Dette kan være endring av en datasettbeskrivelse, eller andre metadata i katalogen.

.Eksempler

* [*] 01.01.2017 00:00

----
<> <http://brreg.no/catalogs/974760673>
     dct:modified “2017-01-01T00:00:00+01:00”^xsd:DateTime .
----
