
== Datasett

=== Hvordan beskrive et datasett?

Denne veilederen beskriver videre hvordan datasett beskrives i henhold til standarden https://doc.difi.no/dcat-ap-no/[DCAT-AP-NO v.1.1]. For å ha med all nødvendig informasjon, er det en del felter som må fylles ut. I det følgende går vi gjennom de enkelte feltene og hvordan disse skal fylles ut.

Eksempel på en beskrivelse av et datasett:
****
*Tittel*: Partiregisteret +
*Datasetteier*: Brønnøysundregistrene +
*Beskrivelse*: Partiregisteret er et register over politiske parti i Norge. Hovedformålet med registeret er å gi parti anledning til å skaffe seg enerett på partinavn. +
*Sentrale opplysninger i datasettet*: Organisasjonsnummer, Parti, Partinavn, Utøvende organ, Kontaktperson +
*Tema*: Offentlig forvaltning +
*Geografisk omfang*: Norge +
*Oppdateringsfrekvens*: Daglig +
*Tilgangsrettigheter*: Offentlig +
*Språk*: Norsk +
*Kontaktpunkt*: Brønnøysundregistrene, partiregisteret@brreg.no +
*Relatert til*: Enhetsregisteret +
*Distribusjon*: +
****
Se felles datakatalog for flere eksempler (https://fellesdatakatalog.brreg.no/[fellesdatakatalog.brreg.no]).


=== Eier av datasettet

.Sammendrag
Skal peke på en Enhet i Enhetsregisteret.

.Anbefalinger
Identifisering av den enheten som er ansvarlig for at datasettet _er_ tilgjengelig, ikke den som faktisk gjør datasettet tilgjengelig. Eier er et obligatorisk felt.

 * Skal peke på en Enhet (juridisk person, organisasjonsledd, underenhet)
 * Det offisielle navnet på virksomheten vil hentes fra Enhetsregisteret, men kortform (f.eks. Difi) kan legges inn av brukeren
 * Eieren av datasettet forvalter sammensetning av dataene, altså datasettet, og ikke nødvendigvis selve dataene.

.Eksempler
* [*] Arbeids- og velferdsdirektoratet
----
<>  dct:publisher <http://data.brreg.no/enhetsregisteret/enhet/889640782> . #NAV
----

=== Skaper av datasettet

.Sammendrag
Brukes unntaksvis der det er datasett som er satt sammen av data som andre er ansvarlige for

.Anbefalinger
Egenskapen angir produsent(er) av datasettet der dette er en annen enn dataeier

 * Brukes unntaksvis der det er datasett som er satt sammen av data som andre er ansvarlige for
 * Skaper vil ikke angis med organisasjonsnummer siden det typisk vil være en sammensatt gruppe.

.Eksempler

* [*] “Kommunene”
----
<>  <http://data.brreg.no/datakatalog/datasett/12>
    dct:creator “Kommunene” .
----
=== Tittel på datasett

.Sammendrag
Tittelen skal være kortfattet, kunne stå alene og gi mening. Organisasjonens navn trenger ikke å være med. Tittelen skal gjenspeile avgrensninger dersom datasettet er avgrenset i populasjonen. Forkortelser skal skrives helt ut.

.Anbefalinger
Datasettet har en tittel slik at det bl.a. kan vises i lister. Tittel er et obligatorisk felt.

 * Tittelen skal være kortfattet, kunne stå alene og gi mening.
 * Organisasjonens navn trenger ikke å være med, med mindre det er spesielt relevant for datasettets innholdsmessige utvalg.
 * Tittelen skal gjenspeile avgrensninger dersom datasettet er avgrenset i populasjonen -  populasjonen er avgrenset av geografi eller formål, f.eks. “... med støtte i Lånekassen”, “... i Oslo”, “ Folketellingen av 1910”. Der populasjonen ikke er avgrenset angis IKKE dette (f.eks. valgkrets)
 * Forkortelser skal skrives helt ut (DTM10 erstattes av “Digital Terrengmodell 10m oppløsning (DTM10)” . Bruk eventuelt feltet for emneord til forkortelser. Målgruppen er personer som ønsker å finne relevante datasett raskt, unngå derfor interne navn eller forkortelser i tittel. I det offentlige opererer man ofte med flere titler eller navn på ting. Et datasett kan ha et offisielt navn, et kortnavn og en forkortelse. For eksempel: Datasettet “Administrative enheter i Norge” har ABAS som forkortelse. Det er sjelden man bruker den fulle tittelen, så for å gjøre et datasett mest mulig søkbart er det behov for at man kan registrere kortnavn, forkortelser og/eller alternative titler.
 * Lov- eller forskriftshjemlede navn bør brukes i tittel (f.eks. Jegerregisteret)

.Eksempler

 * [*] “Bomstasjoner i Norge”
* [ ] [.line-through]#“Statens vegvesens oversikt over Bomstasjoner i Norge”#

* [*] “Digital Terreng Modell 10m oppløsning (DTM10)”
* [ ] [.line-through]#“DTM10”#

=== Formål

.Sammendrag
Beskrivelsen skal være kortfattet og ikke gjentas i Beskrivelsesfeltet.

.Anbefalinger
En setnings-beskrivelse av formålet til datasettet.

 * Det er formålet for opprettelsen eller at datasettet i det hele tatt eksisterer som skal beskrives her
 * Beskrivelsen skal være kortfattet og ikke gjentas i Beskrivelsesfeltet.
 * Dersom datasettet inneholder personopplysninger skal dette feltet brukes for å gjengi det formålet i henhold til personopplysningsloven som ligger til grunn for datasettet.

.Eksempler
* [*] Løsøreregisteret er etablert for å tinglyse heftelser (pant) i løsøre, uten tilknytning til fast eiendom
* [*] Kontakt- og reservasjonsregisteret er etablert for at det offentlige skal kunne kommunisere elektronisk med innbyggerne, og benyttes i forbindelse med saksbehandling og utføring av forvaltningsoppgaver for øvrig, og skal benyttes til varsling etter eforvaltningsforskriftens § 8 tredje ledd. Se eforvaltningsforskriften §§ 29-35

----
<>  dcatno:objective “Løsøreregisteret er etablert for å tinglyse heftelser (pant) i løsøre, uten tilknytning til fast eiendom”@no .
----


=== Beskrivelse av datasett

.Sammendrag
Beskrivelsen skal være kortfattet. Hensikten med datasettet bør komme fram. Hvilke opplysninger som utgjør kjernen i datasettet bør angis. Bruk folkelige ord. Beskriv avgrensninger, hva datasettet ikke inneholder. Begrens lenker og markup.

.Anbefalinger
En kort og presis beskrivelse av datasettet skal gjøre det lett for andre å se hva det inneholder. Beskrivelse er et obligatorisk felt.

 * Beskrivelsen skal være kortfattet slik at lister over datasett forståes ved å lese de første linjene.
 * Hensikten med datasettet bør komme fram (f.eks. “Løsøreregisteret inneholder tinglyste flyttbare eiendeler”).
 * Beskriv hva datasettet inneholder. Hvilke opplysninger som utgjør kjernen i datasettet bør angis.
 * Feltinnhold skal ikke listes, men listes i emneord eller begreper.
 * Beskrivelsen er ikke en gjentakelse av tittel
 * Bruk folkelige ord (f.eks.”Løsøre” må forklares. F.eks. “flyttbare eiendeler (Løsøre)”, ev. bare folkelige uttrykk mens faguttrykket tas med som stikkord slik at det gir treff i søk)
 * Beskriv avgrensninger, hva datasettet ikke inneholder, dersom dette kan misforstås ut fra tittelen.
 * Begrens lenker og markup (formatering) i teksten. Skal man angi språk må teksten formelt sett være fri for lenker og formatering (HTML).
 * Der målform er kjent skal "nb" eller "nn" brukes, "no" brukes ellers.

.Eksempler

* [ ] [line-through]#“Løsøreregisteret inneholder løsøre med unntak av skip og luftfartøy”#
Et lite folkelig ord (løsøre) er brukt. Avgrensningene her er greie

* [ ] [line-through]#“Løsøreregisteret inneholder tinglyste flyttbare eiendeler som biler og båter”#

Hva som inngår i datasettet er godt beskrevet, men unntakene her er utelatt.

* [*] “Løsøreregisteret inneholder tinglyste flyttbare eiendeler med unntak av skip og luftfartøy”


=== Dokumentasjon

.Sammendrag
Referanse til en side som inneholder utdypende dokumentasjon om datasettet.

.Anbefalinger
Utdypende dokumentasjon av datasettet angis ved å peke på en side der den finnes.

.Eksempler


* [*] https://confluence.brreg.no/display/DBNPUB/Informasjonsmodell+for+Enhetsregisteret+og+Foretaksregisteret
----
<> foaf:page
  <https://confluence.brreg.no/display/DBNPUB/Informasjonsmodell+for+Enhetsregisteret+og+Foretaksregisteret> .
----

=== Landingsside

.Sammendrag
Referanse til en side som beskriver datasettetet.

.Anbefalinger

Dokumentasjon om datasettet på en landingsside hos datasetteieren som kan beskrive datasettets innhold og struktur, og tilgang. Det anbefales at Dokumentasjon brukes der man refererer til utfyllende dokumentasjon, og Distribusjon benyttes f.eks. når man vil referere til en søkeside.

 * kan referere til datasettets hjemmeside
 * kan referere til en samleside som beskriver innhold og struktur
 * kan referere til en samleside om nedlasting/bruk/søk (tjenestene)
 * det kan refereres til flere sider

.Eksempler

* [*] https://confluence.brreg.no/display/DBNPUB/Informasjonsmodell+for+Enhetsregisteret+og+Foretaksregisteret
----
<> dcat:landingpage
  <https://confluence.brreg.no/display/DBNPUB/Informasjonsmodell+for+Enhetsregisteret+og+Foretaksregisteret>, <https://www.brreg.no/om-oss/samfunnsoppdraget-vart/registera-vare/einingsregisteret/> .
----

=== Tilgangsnivå

.Sammendrag
Angi om datasettet offentlig åpne data, eller er helt eller delvis skjermet for innsyn.

.Anbefalinger
Det er behov for å angi i hvilken grad datasettet kan bli gjort tilgjengelig for allmennheten, uten hensyn til om det er publisert eller ikke

 * *Angi om datasettet er helt eller delvis skjermet for innsyn*. Offentlig, begrenset offentlighet og unntatt offentlighet.
 * *Skal gjenspeile det mest begrensede feltet/opplysningen i datasettet*
 * “Offentlig” betyr at datasettet ikke inneholder begrensede opplysninger og kan legges ut som åpne data, selv om det ikke er laget en løsning for tilgang. Se https://doc.difi.no/data/veileder-apne-data/[Difis veileder for åpne data].
 * “Begrenset offentlighet” betyr at tilgangen til opplysningene avhenger av hvilket formål opplysningene er innsamlet til, og hvilket lovhjemmel den som skal bruke dataene har. Begrensningen kan skyldes innhold som personopplysninger. Når noen ønsker å benytte datasettet må man foreta en konkret vurdering av tilgangen.
 * “Unntatt offentlighet” betyr saksbehandler har med referanse til lov eller forskrift valgt at  datasett (dokumenter eller saksopplysninger) kan unndras fra offentlighet. Typiske eksempler er interne dokumenter, styringsdialog, ansettelser, gradert informasjon, forretningshemmeligheter eller data som andre eier.
 * *Varianter av datasettet kan være offentlig*** ***ved at det utelater de felt som gjør at det opprinnelige datasettet er begrenset teller unntatt offentlighet.* (se relasjoner mellom datasett)
 * *Ved bruk av verdiene "begrenset offentlighet" og "unntatt offentlighet" er egenskapen skjermingshjemmel anbefalt*

.Eksempler
Enhetsregisteret (hele):

* [*] begrenset offentlighet

Enhetsregisteret - Juridisk person (hovedenhet)

* [*] offentlig

----
<>  dcat:accessRights <http://publications.europa.eu/resource/authority/access-right/PUBLIC>.
----


=== Skjermingshjemmel

.Sammendrag

Angi referanse til relevant lov eller forskrift.

.Anbefalinger
Dersom datasettet har begrensninger på deling trenger vi å vite hva skjermingen gjelder. Det kan være hjemmel (kilde for påstand) i offentlighetsloven, sikkerhetsloven, beskyttelsesinstruksen eller annet lovverk som ligger til grunn for vurdering av tilgangsnivå.

 * Angi referanse til relevant lov eller forskrift. Helst til lovdata på paragraf-nivå.
 * Egenskapen er anbefalt dersom «tilgangsnivå» har verdiene «begrenset» eller «ikke-offentlig»

.Eksempler

* [*] Forvaltningsloven, taushetsplikt §13
* [*]  Offentleglova, Opplysningar som er underlagde teieplikt §13

----
<>   dcatno:legalBasisFor [ .
     skos:prefLabel “Forvaltningsloven, taushetsplikt §13” ;
     rdfs:seeAlso <https://lovdata.no/lov/1967-02-10/§13> .
   ], [
     skos:prefLabel “Offentliglova, taushetsplikt §13” ;
     rdfs:seeAlso <https://lovdata.no/lov/1967-02-10/§13> .
   ] .
----

=== Behandlingsgrunnlag

.Sammendrag
Behandlingsgrunnlag knyttes enten til angitt lovhjemmel, samtykke eller nødvendighetsvurdering.

.Anbefalinger
Etter personopplysningsloven skal det foreligge et grunnlag for behandling av personopplysninger.

 * Dersom et datasett inneholder personopplysninger skal det være et grunnlag for behandlingen.
 * Behandlingsgrunnlag knyttes til alternativene som finnes i forordningens artikkel 6, 9 eller 10. Angi dette i tekst.
 * Dersom behandlingsgrunnlaget forutsetter et supplerende rettslig grunnlag, se artikkel 6(3), skal det angis en referanse til dette rettslige grunnlaget. Helst til lovdata på paragraf-nivå.

.Eksempler

----
<> dcatno:accessRightsComment [
       skos:prefLabel “Treffe vedtak om tjenestepensjon til i hovedsak statsansatte og (kommunale) lærere”@no ;
     rdfs:seeAlso <https://lovdata.no/dokument/NL/lov/1949-07-28-26/KAPITTEL_1#§1> .
] .
----


=== Utleveringshjemmel

.Sammendrag
Henvisning til regelverk som begrunner en offentlig virksomhet sin rett eller plikt til å utlevere opplysninger til andre private personer eller juridiske personer.

.Anbefalinger
Informasjon om utleveringshjemmel gjør det enklere for brukere av datasettet å se om det er nødvendig med egen hjemmel for innhenting eller om de kan få tillatelse til å bruke opplysninger etter søknad til dataeier.

 * Henvisning til regelverk som begrunner en offentlig virksomhet sin rett eller plikt til å utlevere opplysninger til andre private personer eller juridiske personer.
 * Henvisningen gjøres til lovdata på paragraf-nivå.

.Eksempler
----
<>   dcatno:accessRightsComment [
       skos:prefLabel “behandling av helseopplysninger i nasjonal kjernejournal, personaljournalloven §13”@no ;
     rdfs:seeAlso <https://lovdata.no/lov/2014-06-20-42/§13> .
] .
----


=== Tema

.Sammendrag
Ett eller flere temaer velges fra den kontrollerte listen av EU-temaer

.Anbefalinger
For å kunne sortere datasettet inn under gitte kategorier er det behov for tema

 * Ett eller flere temaer velges fra http://publications.europa.eu/mdr/authority/data-theme/index.html[den kontrollerte listen av EU-temaer].

.Eksempler

* [*] *Helse* (lenke: http://publications.europa.eu/mdr/authority/data-theme/HEAL)

----
<>  <http://data.brreg.no/datakatalog/datasett/12>
     dcat:theme <http://publications.europa.eu/mdr/authority/data-theme/HEAL> .
----


=== Type

.Sammendrag
Referanse til en klassifisering av datasettets type innhold. Refererer til EU publication office sine datasett-typer

.Anbefalinger
Referanse til en klassifisering av datasettets type innhold. Refererer til EU publication office sine datasett-typer.

 * Datasett som anses som å inneholde data angis med “Datasett”
 * Datasett som anses som metadata (f.eks. Kodelister, Taksonomier og Tesauri) skal angis tilsvarende
 * Datasett som anses som testdata angis som “Testdata”

.Eksempler
----
<> dct:type <http://publications.europa.eu/resource/authority/dataset-type/CODE_LIST> .

<>  dct:type
<http://data.brreg.no/datasettype/Datasett> .

<> dct:type
<http://data.brreg.no/datasettype/TestDatasett> .

----


=== Begrep

.Sammendrag

Innholdstyper i datasettet beskrives med referanse til begreper i begrepskatalog

.Anbefalinger

For å beskrive viktigste typer innhold i datasettet refereres det til begreper i begrepskataloger som også gir mulighet til å utnytte synonymer

 * innholdstyper i datasettet beskrives med referanse til begreper i begrepskatalog
 * dersom det ikke kan benyttes en begrepskatalog brukes emneord.

Et datasett skal lenke til de aktuelle og sentrale begrepene i en begrepskatalog. Ved å henvise til gjennomarbeidede definisjoner som virksomheten selv er ansvarlig for å vedlikeholde, sikrer vi at det er tydelig hvordan et begrep brukt i datasettet skal forstås og at denne forståelsen til en hver tid er riktig og oppdatert. Vi ønsker at alle datasettene skal ha lenker til de aktuelle begrepene i virksomhetens katalog, slik at det er tydelig definert hva begrepene innebærer

I Referansekatalogen finner du relevante standarder for arbeidet med begrepsdefinisjoner:
https://www.difi.no/artikkel/2015/10/begrepsanalyse-og-definisjonsarbeid[https://www.difi.no/artikkel/2015/10/begrepsanalyse-og-definisjonsarbeid]

.Eksempler

* [*]  [.underline]#Løsøre#, [.underline]#Pant#, [.underline]#Tinglysing#
----
<> <http://data.brreg.no/datakatalog/datasett/12>
    dct:subject <http://brreg.no/begrepskatalog/begep/løsøre>,
                <http://brreg.no/begrepskatalog/begep/pant>,
                <http://brreg.no/begrepskatalog/begep/tingslysning> .
----

=== Søkeord

.Sammendrag
Angi synonymer og andre ord som kan hjelpe i søk. Sentralt innhold i datasettet som ikke ennå har begrepsdefinisjoner.

.Anbefalinger
Ord og uttrykk som hjelper brukeren til å finne datasettet inkluderes (der det ikke er eksplisitt angitt referanser til begreper)

 * Angi synonymer til hjelp i søk
 * Angi sentralt innhold i datasettet som ikke finnes begrepsdefinisjoner for ennå

I noen tilfeller mangler noen av begrepsdefinisjonene som er sentrale for å beskrive datasettet, eller man har et ord som ikke formelt forbindes med datasettet men som man vet at mange likevel bruker. Da kan vi bruke dette feltet for å sørge for at disse søkeordene likevel gir treff i søkemotoren.

.Eksempler

* [*] uførepensjon, uførepensjonister, uførereform
----
<http://data.brreg.no/datakatalog/datasett/12>
     dcat:keyword “uførepensjon”@no, “uførepensjonister”@no, “uførereformen”@no .
----


=== Geografisk avgrensing

.Sammendrag
Angi geografisk avgrensning dersom datasett kun har innhold fra visse områder. Referer til geografiske områder angitt med URI fra Statens Kartverk eller GeoNames

.Anbefalinger
Det er ønskelig å synliggjøre om datasettets utvalg er begrenset til bestemte geografiske områder.

 * Angi geografisk avgrensning dersom datasett kun har innhold fra visse områder. “Observert hekking av grågås i Oppdal” er datasettets geografiske omfang begrenset til kommunen Oppdal.
 * Benytt eksisterende avgrensninger som kommuner, fylker m.v.
 * Bør referere til geografiske områder angitt. Med URI-er (f.eks. Sentralt Stedsnavnsregister eller Administrative grenser fra Kartverket)
 * Flere områder kan angis om relevant
 * Dersom det finnes en tilsvarende landsdekkende oversikt, bør dette beskrives som et separat datasett, og disse relateres  f.eks. "Observert hekking av grågås i Norge"

.Eksempler

* [*] [.underline]#Oppdal# (lenke: http://data.geonorge.no/administrativeEnheter/kommune/id/172879)
* [*] [.underline]#Oppdal# (lenke: http://sws.geonames.org/3143508/)
----
# eksempel på lenker til EU publication office (SKOS)
<> dct:spatial <http://publications.europa.eu/resource/authority/country/NOR>
             a dct:Location, skos:Concept ;
             skos:prefLabel “Norge”@no .

# eksempel på lenker til GeoNames
<> dct:spatial <http://sws.geonames.org/3144096/>
             a gn:Feature ;
             gn:officalName “Norge”@no .

# eksempel på lenker til Kartverket (kommer)
----

=== Tidsmessig avgrensing

.Sammendrag
Angi tidsmessig avgrensning dersom datasett kun har innhold fra visse perioder. Dersom det finnes en tilsvarende komplett oversikt, bør også dette beskrives som et eget datasett

.Anbefalinger
En tidsromangivelse er nødvendig for datasett hvor innholdet dekker et avgrenset tidsrom.

 * Angi tidsmessig  avgrensning dersom datasett kun har innhold fra visse perioder. For mange datasett knyttet til registerfunksjoner vil tidsrom være direkte koblet mot oppdateringsfrekvens. For andre datasett vil tidsrom være vesentlig i forhold til forståelse av bruk av dataene, f.eks folketellinger.
 * Dersom det er angitt en periode med årstall, tolkes dette som fra og med 1. januar første år til og med 31. desember siste år.
 * Ved ett årstall på begynnelse, men ikke angitt slutt, tolkes det at datasettet har data også i en ubestemt fremtid og tilsvarende om startdatoen mangler antas det at det er ikke angitt om datasettet har en start.
 * Dersom det finnes en tilsvarende komplett oversikt, bør også dette beskrives som et eget datasett, og disse relateres.
 * Dersom datasettet er en av flere i en tidsserie anbefales det at det lages et overordnet datasett for tidsserien uten distribusjoner som peker på hver datasett.
 * Det benyttes tidsstempel for registreringen av første og siste dataelement i datasettet.
 * Det kan angis flere tidsperioder per datasett, men det anbefales at periodene ikke er overlappende.
 * _Relativ avgrensning i tid fra tidspunkt for uttrekk (eksempelvis fra og med dato for forrige påbegynte semester og til og med avslutning av påfølgende semester)_

.Eksempler

* [*] “1901”
----
<> <http://data.brreg.no/datakatalog/datasett/12>
    dct:temporal  [
        a dct:PeriodOfTime ;
        ot:hasBeginning  [
            a ot:Instant ;
            ot:inXSDDateTime "1901-01-01T00:00:00Z"^^xsd:dateTime
        ] ;
        owl:hasEnd [
            a ot:Instant ;
           ot:inXSDDateTime  "1901-12-31T00:00:00Z"^^xsd:dateTime
       ]
   ] .
----


=== Utgivelse

.Sammendrag
Tidspunktet angir når innholdet i datasettet gjøres tilgjengelig.

.Anbefalinger
For å forstå når datasettet er operativt og tilgjengelig angis tidspunkt for utgivelse.

 * Angis som tidspunkt (dato alene tolkes som kl. 00:00)
 * Tidspunktet angir når innholdet i datasettet gjøres tilgjengelig. Dette er ikke alltid  samsvarende med når den enkelte distribusjonen er tilgjengelig. Og heller ikke når beskrivelsen om datasettet utgis (katalogpostens utgivelse).
 * Tidspunkt angis med xsd:dateTime. Dette inkluderer utvidelser av kapittel 5.4 i ISO 8601 med tidssoner) [-]CCYY-MM-DDThh:mm:ss[Z|(+|-)hh:mm]

.Eksempler

* [*] 01.01.2017 00:00
----
<> <http://data.brreg.no/datakatalog/datasett/12>
     dct:issued “2017-01-01T00:00:00+01:00”^xsd:DateTime .
----

=== Språk

.Sammendrag
Hovedspråket benyttet i datasettets innhold angis

.Anbefalinger
For å forstå hvilket språk innholdet til datasettet har angis dette

 * Det er hovedspråket benyttet i datasettets innhold som skal angis
 * Er datasettet uten språklige tekster angis ikke språk
 * Inneholder datasett tekster på flere språk, og det ikke er tydelig hva som er hovedspråket, angis ikke språk
 * Språk angis fra en liste av gyldige språk fra EUs autoritetsliste.

.Eksempler

* [*] Norsk

----
<> <http://data.brreg.no/datakatalog/datasett/12>
     dct:language <http://publications.europa.eu/resource/authority/language/NOR> .
----

=== Opphav


.Sammendrag
Angi om opplysningene i datasettet er resultat av vedtak eller innsamlet fra bruker eller tredjepart

.Anbefalinger
Det er behov for en sortering om innholdet er basert på avgjørelse truffet under utøvelse av offentlig myndighet (vedtak) eller er kommer fra andre kilder (bruker eller tredjepart). Vedtak anses å være autoritative kilder for hele forvaltningen.

 * Angi om opplysningene i datasettet er resultat av vedtak eller innsamlet fra bruker eller tredjepart
 * Det skal velges en verdi fra et kontrollert vokabular med verdiene Vedtak, Bruker og Tredjepart

Enkelte offentlige virksomheter har datasett som innen sitt område eller nasjonalt er å anse autoritative kilder. Eksempler på slike datasett er Enhetsregisteret (ER), Folkeregisteret (DSF), Matrikkelen og Aa-registeret.  Per i dag er de tre første formelle grunndataregistre, men det er flere andre datasett som i større eller mindre grad blir gjenbrukt innenfor sektorer eller generelt innenfor offentlig sektor og resten av samfunnet.

.Eksempler

* [*] Vedtak
----
<> dct:provenance <http://data.brreg.no/opphav/vedtak>
----

=== Oppdateringsfrekvens

.Sammendrag
Beskriv hvor ofte datasettet har nytt innhold

.Anbefalinger
En angivelse hvor ofte datasettet blir oppdatert.

 * Beskriv hvor ofte datasettet har nytt innhold. For eksempel oppdateres Enhetsregisteret med nye enheter og sletting av enheter _kontinuerlig_, mens Inntektsdata fra likningen (Skattemelding) er _årlig_ og Folketelling fra 1910 oppdateres _aldri_.
 * Begreper (og tilhørende URIer) fra http://publications.europa.eu/mdr/authority/frequency/index.html[Frequency Name Authority List] skal benyttes

.Eksempler

----
<> dct:accruralPeriodicity  <http://publications.europa.eu/resource/authority/frequency/MONTHLY>
----

=== Sist oppdatert

.Sammendrag
Tidspunktet angir når innholdet i datasettet sist er endret.

.Anbefalinger
For å forstå når datasettet sist ble oppdatert angis tidspunkt for siste endring

 * Tidspunktet angir når innholdet i datasettet sist er endret.
 * Angis som tidspunkt (dato alene tolkes som kl. 00:00:00 norsk tid)
 * Tidspunkt angis med xsd:dateTime etter kapittel 5.4 i ISO 8601 utvidet med tidssoner [-]CCYY-MM-DDThh:mm:ss[Z|(+|-)hh:mm]

.Eksempler

* [*] 01.01.2017 00:00

----
<> <http://data.brreg.no/datakatalog/datasett/12>+
----

=== Aktualitet

.Sammendrag

Avvik eller tilleggsopplysninger om “oppdateringsfrekvens” og “sist oppdatert”

.Anbefalinger
Avvik eller tilleggsopplysninger om “oppdateringsfrekvens” og “sist oppdatert”

 * Er opplysninger om “oppdateringsfrekvens” og “sist oppdatert” alltid gyldig? Er det opplysninger i datasettet som har annen oppdateringsfrekvens?

.Eksempler

----
<> dqv:hasQualityAnnotation [
    a dqv:QualityAnnotation ;  # kvalitetsnote
    dqv:inDimension iso:Currentness ;
    oa:hasBody [
       rdf:value=”Enhetsregisteret er kontinuerlig oppdatert, men egenskapen antall ansatte oppdateres månedlig fra Aa-registeret”@no;
    ] .
  ] .
----

=== I samsvar med standard

.Sammendrag
Angi at et datasett er i samsvar med en standard, spesifikasjon eller implementasjonsregel.

.Anbefalinger
Det er behov for å vite om et datasett er i henhold til gitt(e) standard(er).

 * Benyttes til å angi at et datasett er i samsvar med en standard, spesifikasjon eller implementasjonsregel. Eksempel: Et datasett er i samsvar med SOSI 4.5 som  innholdsstandard.
 * For referanser til maskinlesbare informasjonsmodeller, skal egenskapen “informasjonsmodell benyttes”

.Eksempler
----
<> dcat:conformsTo [
  skos:prefLabel “Produktspesifikasjon NVE flomsoner 1.0”@no
  rdfs:seeAlso <http://sosi.geonorge.no/Produktspesifikasjoner/Produktspesifikasjon_NVE_Flomsoner_1%200.pdf>
] .
----

=== Relevans

.Sammendrag
Avvik eller tilleggsopplysninger knyttet til datasettes relevans i ulike brukskontekster

.Anbefalinger
Avvik eller tilleggsopplysninger knyttet til datasettes relevans i ulike brukskontekster
 * En vurdering om det er bruksområder datasettet er spesielt velegnet eller ikke bør brukes.

.Eksempler

----
<> dcatno:hasQualityAnnotation [
    a dqv:QualityAnnotation ;
    dqv:inDimension iso:Relevance ;
    oa:hasBody [
       rdf:value=”Enhetsregisterets Næringskode viser enhetenes hovedaktivitet og skal primært dekke statistiske behov for Statistisk sentralbyrå (SSB). Næringskoden er satt ved opprettelse av selskapet, og reflekterer ikke alltid selskapets endrede forretningsmodell.”@no;
    ] .
  ] .

----

=== Kompletthet

.Sammendrag
I hvilken grad inneholder datasettet alle objekter som nevnt i formålet.

.Anbefalinger
I hvilken grad inneholder datasettet forventede opplysninger

 * Kompletthet tolkes i forhold til formålet (utvalget)
 * Inneholder datasettet de objekter som nevnt i formålet?

.Eksempler

Enhetsregisteret - formålet er effektiv utnyttelse og samordning av offentlige opplysninger om juridiske personer, enkeltpersonforetak og andre registreringsenheter

* [*] Enhetsregisteret inneholder ikke slettede selskaper før 1994.

----
<> dqv:hasQualityAnnotation [
    a dqv:QualityAnnotation ;
    dqv:inDimension iso:Completeness ;
    oa:hasBody [
       rdf:value=”Enhetsregisteret inneholder ikke slettede selskaper før 1994.”@no;
    ] .
  ] .
----


Kontakt og reservasjonsregisteret - formål benyttes til varsling og kan benyttes i forbindelse med saksbehandling og utføring av forvaltningsoppgaver for øvrig

* [*]  Alle innbygger er ikke representert/registrert

----
<> dqv:hasQualityAnnotation [
    a dqv:QualityAnnotation ;
    dqv:inDimension iso:Completeness ;
    oa:hasBody [
       rdf:value=”Alle innbygger er ikke representert/registrert.”@no;
    ] .
  ] .
----

=== Nøyaktighet

.Sammendrag
I hvilken grad er innholdet i samsvar med formålet

.Anbefalinger
I hvilken grad representerer datasettet korrekt intensjonen som er angitt av dataeier i formålet

 * Nøyaktighet skal tolkes i forhold til formålet.
 * Angi om det er begrensninger i forhold til formålet

.Eksempler
Regnskapsregisteret - Formålet med ordningen er å sikre økonomisk trygghet og effektivitet – mellom selskapene og myndighetene, mellom selskapene og publikum, og ikke minst, selskapene imellom.

* [*] Enhetens regnskap blir ikke kontrollert av Regnskapsregisteret.

----
<> dqv:hasQualityAnnotation [
    a dqv:QualityAnnotation ;
    dqv:inDimension iso:Accuracy ;
    oa:motivatedBy dqv:qualityAssessment ;
    oa:hasBody [
       rdf:value=”Enhetens regnskap blir ikke kontrollert av Regskapsregistert.”@no;
    ] .
    ] .
----

Kontakt og reservasjonsregisteret - formål benyttes til varsling og kan benyttes i forbindelse med saksbehandling og utføring av forvaltningsoppgaver for øvrig

* [*] Brukere har selv oppgitt informasjon, sjekkes med SMS.

----
<> dqv:hasQualityAnnotation [
    a dqv:QualityAnnotation ;
    dqv:inDimension iso:Accuracy ;
    oa:motivatedBy dqv:qualityAssessment ;
    oa:hasBody [
       rdf:value=”Brukere har selv oppgitt informasjon, sjekkes med SMS.”@no;
    ] .
  ] .
----

Askeladden - Riksantikvarens offisielle database over fredete kulturminner og kulturmiljøer i Norge

* [*] Arkeologiske funn som er registrert før år 2005 har feilmargin på stedfesting på opptil 10 meter. Funn registrert etter 2005 har feilmargin på opptil 0,5 meter

----
<> dqv:hasQualityAnnotation [
    a dqv:QualityAnnotation ;
    dqv:inDimension iso:Accuracy ;
    oa:motivatedBy dqv:qualityAssessment ;
    oa:hasBody [
       rdf:value=”Arkeologiske funn som er registrert før år 2005 har feilmargin på stedfesting på opptil 10 meter. Funn registrert etter 2005 har feilmargin på opptil 0,5 meter”@no;
    ] .
  ] .
----

=== Tilgjengelighet

.Sammendrag
Avvik eller tilleggsopplysninger knyttet til datasettes tilgjengelighet

.Anbefalinger
Avvik eller tilleggsopplysninger knyttet til datasettets tilgjengelighet

 * Tilgjengelighet tolkes i forhold til tilgangsnivå og ev. begrensninger utover det som er angitt i behandlingsgrunnlag, skjermings- og utleveringshjemmel.
 * Dersom datasettet er åpent men mangler distribusjoner bør årsaken angis her.

.Eksempler

----
<> dqv:hasQualityAnnotation [
    a dqv:QualityAnnotation ;
    dqv:inDimension iso:Availability ;
    oa:hasBody [
       rdf:value=”Regnskapsregisteret kan kun hentes ut på forespørsel”@no;
    ] .
    ] .
----

=== Informasjonsmodell

.Sammendrag
Refereranse til datasettets informasjonsmodell

.Anbefalinger
En eksplisitt referanse til informasjonsmodell

 * Benyttes til å angi en maskinlesbar referanse til informasjonsmodell.

.Eksempler

----
<> dcatno:informationModel [
   skos:prefLabel “Informasjonsmodell Flomsoner 1.0”@no ;
   rdfs:seeAlso <https://objektkatalog.geonorge.no/Pakke/Index/EAPK_C8C565A7_B07B_41ec_80B0_1A2EEEBA0C15> ] .
----


=== Kilde datasett (avledet fra)

.Sammendrag
Peker til ressurs (datasett eller annet) som helt eller delvis er en kilde for det aktuelle datasettet.

.Anbefalinger
Peker til en ressurs som er kilde til datasettet

 * Peker til ressurs (datasett eller annet) som helt eller delvis er en kilde for det aktuelle datasettet. F.eks. kan et datasett er opprettet basert på data som er hentet fra en nettside, uten at den er definert som et datasett.
 * Dersom et åpent datasett er basert på et annet hvor personopplysninger er fjernet, kan relasjonen brukes.
 * Et datasett som er avledet fra et annet skal ha en referanse til kilde for det aktuelle datasettet.
 * Dersom det er et utvalg fra et annet datasett bør heller relasjonen _del av_ brukes

.Eksempler

----
<> dcat:source [
   skos:prefLabel “Det sentrale folkeregisteret”@no ;
   rdfs:seeAlso <http://brreg.no/catalogs/974761076/datasets/e3fc94e4-cc7e-4290-b479-4e0c99dc6caa> ] .
----

=== Del av datasett

.Sammendrag
Der registre oppdeles i mindre datasett skal relasjonen brukes.

.Anbefalinger
Peker til et datasett som det aktuelle datasettet er en delmengde av av, eller at det er brutt opp i mindre datasett.

 * Der registre oppdeles i mindre datasett skal relasjonen brukes. F.eks. er datasettet Underenheter er del av datasettet Enhetsregisteret.

.Eksempler

----
<> dct:isPartOf [
   skos:prefLabel “Det sentrale folkeregisteret”@no ;
   rdfs:seeAlso <http://brreg.no/catalogs/974761076/datasets/e3fc94e4-cc7e-4290-b479-4e0c99dc6caa> ] .
----

=== Erstattet av datasett

.Sammendrag
Peker til et datasett som erstatter et aktuelt datasettet

.Anbefalinger
Peker til et datasett som erstatter et aktuelt datasettet.

 * F.eks. kan et kodeverk bli erstattet av en nyere utgave.

.Eksempler

----
<> dct:isReplacedBy [
   skos:prefLabel “Bydeler fra 1.1.2004”@no ;
   rdfs:seeAlso <https://data.norge.no/node/1115> ] .
----

=== Påkrevd av datasett

.Sammendrag
Peker til en ressurs som må være tilstede for at datasettet skal kunne produseres

.Anbefalinger
Peker til en ressurs som må være tilstede for at datasettet skal kunne produseres.

 * Peker til ressurs (datasett eller annet) som aktuelt datasett er avhengig av

.Eksempler
----
<> dct:isPartOf [
   skos:prefLabel “Postnummer i Norge”@no ;
   rdfs:seeAlso <https://data.norge.no/node/1252> ] .
----

=== Refererer til

.Sammendrag
Referanse til andre datasett som det kan være nyttig for brukere å være oppmerksom på.

.Anbefalinger
Referanse til andre datasett som det kan være nyttig for brukere å være oppmerksom på

 * Peker til datasett som kan være aktuelt å se i sammenheng med det aktuelle datasettet, f.eks. for Enhetsregisteret supplerende informasjon om Enheter, men ikke direkte relatert.

.Eksempler
----
<> dct:references [
   skos:prefLabel “Register over offentlig støtte”@no ;
   rdfs:seeAlso <http://brreg.no/catalogs/974760673/datasets/ca04abdd-6327-4833-bd05-7a3dca20e6a5> ] .
----

=== Relatert

.Sammendrag
Referanse til andre datasett som gir supplerende informasjon om innholdet.

.Anbefalinger
En generell relasjon som peker til ressurser som er relatert til datasettet.

 * Angi referanser til andre datasett som gir supplerende informasjon om innholdet. Kan f.eks. være å relatere til et annet register.

.Eksempler

----
<> dct:relation [
    skos:prefLabel “Det sentrale folkeregisteret”@no ;
   rdfs:seeAlso <http://brreg.no/catalogs/974761076/datasets/e3fc94e4-cc7e-4290-b479-4e0c99dc6caa> ] .
----


=== Versjon av

.Sammendrag
Referanse til et datasett som i prinsippet er det samme, men hvor innholdet er blitt oppdatert på bakgrunn av bedret datakvalitet e.l.

.Anbefalinger

Peker til et datasett som det aktuelle datasettet er en versjon av.

 * I prinsippet det samme datasettet, men hvor innholdet er blitt oppdatert på bakgrunn av bedret datakvalitet e.l.
 * Peker til en versjon av det aktuelle datasettet kan avledes (har versjon).

.Eksempler
----
<> dct:isVersionOf [
   skos:prefLabel “Bydeler fra 1.1.2004”@no ;
   rdfs:seeAlso <https://data.norge.no/node/1115> ] .
----

=== Testdatasett

.Sammendrag
For å angi at et register eller datasett foreligger som testdata, typisk syntetiske eller anonymiserte, angis dette med relasjonen testdatasett til et annet datasett.

.Anbefalinger
For å angi at et register eller datasett foreligger som testdata, typisk syntetiske eller anonymiserte, angis dette med relasjonen testdatasett til et annet datasett.

 * Peker til datasett som er består av testdata til det aktuelle datasettet

.Eksempler
----
<> dct:isVersionOf [
   skos:prefLabel “Syntetiske folkeregisteredata”@no ;
   rdfs:seeAlso <http://brreg.no/catalogs/974761076/datasets/e3fc94e4-cc7e-4290-b479-4e0c99dc6caa/> ] .
----

=== Kontaktpunkt

.Sammendrag
Angi kontaktinformasjonen som kan brukes ved henvendelser om et datasett.

.Anbefalinger
Egenskapen kontaktpunkt angis for å komme i dialog med eieren av datasettet.

 * Angi kontaktinformasjonen som kan brukes ved henvendelser om et datasett.
 * Vcard https://www.w3.org/TR/vcard-rdf[https://www.w3.org/TR/vcard-rdf] benyttes for å beskrive kontaktpunktet (se anbefaling under hvert Kontaktpunkt-felt)

.Eksempler

* [*] Avdeling Digitalisering

----
<> <http://data.brreg.no/datakatalog/datasett/12>
    dcat:contactPoint <http://data.brreg.no/datakatalog/kontaktpunkt/a-7> .
----

=== Datasettdistribusjon

.Sammendrag
For å angi hvor man kan få tilgang til datasettet skal det angis ulike distribusjoner.

.Anbefalinger
For å angi hvor man kan få tilgang til datasettet skal det angis ulike distribusjoner.

 * Det angis i utgangspunktet en distribusjon per fil, feed eller API
 * Dersom det er ett API som leverer flere filformater angis det som en distribusjon

.Eksempler
----
 <> <http://brreg.no/catalogs/974760673/datasets/63086dda-9b72-43f0-bbc2-3ced4bc2edd6>
    dcat:distribution <http://data.brreg.no/datakatalog/distribusjon/12>
. # til et beskrivelse av et API
----

=== Eksempeldata

.Sammendrag
Benyttes for å gi eksempeldata for et datasett, og hvordan en faktisk distribusjon ser ut.

.Anbefalinger
Benyttes for å gi eksempeldata for et datasett, og hvordan en faktisk distribusjon ser ut.
 * Dersom datasettet inneholder personopplysninger vil det være nyttig for bruker å se en eksempedata som viser en anonymisert rad i datasettet.

.Eksempler

----
<> <http://brreg.no/catalogs/974761076/datasets/e3fc94e4-cc7e-4290-b479-4e0c99dc6caa>
    dcat:distribution <http://data.brreg.no/datakatalog/distribusjon/124312>
. # til et beskrivelse av en eksempel-distribusjon av folkeregisteret
----
