
== Hva er et datasett?

“Et _datasett_ er en samling med data (for eksempel i form av en tabell, liste eller en database)  som kan gjøres tilgjengelig som en nedlastbar fil, og/eller nåes via et Web-API (definert som _en organisert samling av data_).” Se forøvrig ordforklaringene til https://doc.difi.no/dcat-ap-no/#_ord_uttrykk_og_forkortelser[Standard for beskrivelse av datasett og datakataloger] (DCAT-AP-NO).

Veilederen kan også benyttes til å beskrive ustrukturerte samlinger av data, men hovedhensikten og dermed eksemplene i denne veilederen er utelukkende basert på beskrivelser av _strukturerte_ datasett.

Det kan være vanskelig å vurdere hva som er samling av data og dermed hvor stor eller liten samlingen skal være. Kriterier for å avgrense et datasett vil kunne variere mellom virksomheter og over tid. Se https://www.difi.no/artikkel/2016/06/erfaringer-med-bestemme-hva-et-datasett-er-og-hvilke-datasett-som-skal-beskrives[Brønnøysundregistrenes tanker rundt dette].

Eksempler på avgrensing av et datasett:

 * Enhetsregisteret: Med tanke på datadeling med andre, betrakter Brønnøysundregistrene ikke hele Enhetsregisteret som ett stort datasett, men deler videre Enhetsregisteret inn i datasettene Juridisk Person, Virksomhet/Bedrift, Roller. I tillegg kan tilgangsnivå skille Roller i to datasett; ett komplett, og et der sensitive data er fjernet.
 * I Matrikkelen er datasettene Eiendom, Adresse, Bygning. Datasettene distribueres i henhold til ulike applikasjonsskjema (informasjonsmodeller) og på ulike formater.
 * Aa-registeret inneholder datasettet Arbeidsforhold - kilde: A-ordningen, relasjon til Enhetsregisteret og DSF.
 * Det sentrale folkeregisteret (DSF) inneholder Innbyggere, andre personer med tilknytning til riket, bosted, samemantall osv.
 * Uføre (vedtak om uførestatus) fra NAV er en avgrensning av populasjonen og dermed et datasett.
 * Lovlig opphold fra UDI er et datasett
 * Vernepliktige er etter lov om verneplikt en del av Forsvarets verneplikts- og tjenesteregister.

=== Hvordan starte?

Det er naturlig å fokusere på å beskrive datasett som oppfattes å være knyttet til virksomhetens kjerneoppgaver. Disse vil trolig være av interesse for flere enn interne anliggender. Gjennom tilbakemeldinger og etterspørsel etter de datasettbeskrivelsene man har publisert, har man grunnlag for prioritering av arbeid med å gjøre datasettene tilgjengelig. Det er også naturlig å beskrive data man allerede deler.

 * starte med hele registeret og få det beskrevet
 * avhengig av brukerbehov, tilgjengeliggjøring (distribusjon) og formål dele det inn i mindre datasett (subsett)

=== Hvor dypt skal man gå i nedbrytingen?

Hvis datasettet ditt er veldig stort og omfattende i den forstand at det omhandler flere ulike tema, kan det være hensiktsmessig å se etter måter å dele det opp på. Slik kan det bli mer håndterbart og enklere å sette seg inn i for brukerne.

Hvis datasettet ditt for eksempel omfatter kjøretøy, dets eiere og registrerte mangler, kan det vært bedre å dele dette opp i tre datasett. Når man deler opp datasett på denne måten bør man bruke relasjoner i DCAT til å angi sammenhengen mellom de ulike datasettene.
