
NOTE: For normative beskrivelser av feltene som er omtalt i dette dokumentet, se DCAT-AP-NO: https://doc.difi.no/data/dcat-ap-no-stotte-til-teknisk-implementering/[Støtte til teknisk implementering av dcat-ap-no]

== Innledning

=== Bakgrunn

Digital Agenda og Digitaliseringsrundskrivet viser til målet om at brukeren (privatperson, offentlig og privat virksomhet og frivilligheten) ikke skal trenge å avgi informasjon som han allerede har avgitt. I https://lovdata.no/dokument/NL/lov/1997-06-06-35#shareModal[Lov om Oppgaveregisteret] § 5 stilles det krav til statlige virksomheter at informasjon fra næringslivet er samordnet slik at man ikke etterspør samme informasjon flere ganger. Det langsiktige målet er at gjenbruk er hovedregel.

Den enkelte offentlige virksomhet har etter https://www.regjeringen.no/no/dokumenter/digitaliseringsrundskrivet/id2569983/[Digitaliseringsrundskrivet] (spesielt punkt 1.3) krav til å holde en oversikt over hvilke data de forvalter. Videre legger Regjeringens https://www.regjeringen.no/id2536870/[Retningslinjer ved tilgjengeliggjøring av offentlige data] opp til at offentlige data skal dokumenteres og synliggjøres slik at de er enkle å oppdage, vurdere og eventuelt ta i bruk til nye formål.

Difi forvalter et https://www.difi.no/fagomrader-og-tjenester/digitalisering-og-samordning/nasjonal-arkitektur/informasjonsforvaltning[felles offentlig rammeverk for informasjonsforvaltning] som inneholder veiledere, spesifikasjoner og standarder som er  relevante for informasjonsforvaltning i offentlig sektor. En https://www.difi.no/fagomrader-og-tjenester/digitalisering-og-samordning/nasjonal-arkitektur/informasjonsforvaltning/veileder-orden-i-eget-hus[Veileder for orden i eget hus] er laget for å støtte arbeid med å etablere en praksis for dette i egen virksomhet og en https://www.difi.no/fagomrader-og-tjenester/digitalisering-og-samordning/nasjonal-arkitektur/informasjonsforvaltning/faglig-arena-informasjonsforvaltning[faglig arena for informasjonsforvaltning] etablert av Difi for å gi erfaringsutveksling mellom de offentlige virksomhetene.

Offentlige virksomheter forvalter store mengder opplysninger fordelt på mange registre. For at offentlige virksomheter skal utnytte informasjon fra andre ved utvikling av digitale brukerrettede tjenester, trenger de å vite hvilken informasjon som finnes og kan gjenbrukes. De behøver å kjenne til hvilke datasett som finnes, og evaluere om de er riktige til sitt formål. Til dette trengs egne oversikter å eksponeres utenfor virksomheten. Private virksomheter trenger en oversikt for å kunne finne, forstå og nyttiggjøre seg av åpne data til transparens, innovasjon og næringsutvikling, og få tilgang til opplysninger som kan bedre brukers prosess i private løsninger (myData) der deling skjer med brukers samtykke.

En felles oversikt etableres med Felles datakatalog. DCAT-AP v1.1 er den gjeldende europeiske spesifikasjonen for beskrivelser av datasett og datakataloger. Formålet er å gjøre det enklere å søke etter åpne datasett på tvers av dataportaler i EUs medlemsstater. En norsk versjon kalt https://doc.difi.no/dcat-ap-no/[DCAT-AP-NO] 1.1 er basert på den europeiske. Den norske standarden inneholder utvidelser som er nyttig for også å beskrive datasett som ikke er åpne.

=== Veilederen

==== Mål og hensikt

Denne veilederen skal bidra til bedre beskrivelser av datasettene som virksomhetene i offentlig sektor forvalter, som en del av prosessene for å skape orden i eget hus, oppnå mer gjenbruk av data mellom offentlige virksomheter  og å gjøre mer åpne offentlige data tilgjengelig for næringsliv og sivilsamfunn. Veilederen tar ikke stilling til hvordan du skal kartlegge hvilken informasjon din virksomhet forvalter. For kartlegging av informasjon i din virksomhet, kan bl.a. Difis veileder for http://internkontroll.infosikkerhet.difi.no/[Internkontroll i praksis - informasjonssikkerhet] brukes.

Denne veilederen er laget for å gi en hjelp til at innholdet fra virksomhetene beskrives slik at de kan utnyttes godt av andre. Veilederen skal hjelpe de offentlige virksomhetene å beskrive sine data i henhold til forvaltningsstandarden https://doc.difi.no/dcat-ap-no/[DCAT-AP-NO].

==== Struktur

Digitaliseringsrundskrivet sier

[quote, Digitaliseringsrundskrivet 2017]
Den enkelte virksomhet skal ha oversikt over hvilke data den håndterer,  hva dataene betyr, hva de kan brukes til, hvilke prosesser de inngår i, og hvem som kan bruke dem (informasjonsforvaltning). +
I samsvar med viderebruksbestemmelsene i offentleglova skal virksomheten gjøre egnet informasjon tilgjengelig i maskinlesbare formater, fortrinnsvis gjennom API'er.

Strukturen på veilederen er bygget opp i henhold til dette. Veilederen skal bidra til å beskrive bedre bl.a.

 . Hvilke datasett man har?
 . Hvem forvalter datasettene?
 . Hva er opphavet til dataene?
 . Til hvilket formål er de samlet inn?
 . Hvilke tjenester kan man benytte for å få tilgang til dataene?
 . Er dataene autoritative?

Vedlegg A gir normative definisjoner av feltene.

==== Målgruppe

Målgruppen for denne veilederen er primært deg som skal bruke DCAT-AP-NO til å beskrive datasett og datakataloger i din virksomhet.

Sekundært kan også veilederen brukes av deg som skal utvikle/tilpasse verktøystøtte i virksomhetene for beskrivelser av datasett/datakataloger og/eller eksponering av slike beskrivelser i henhold til DCAT-AP-NO.
