= Forvaltningsregime [[Forvaltningsregime]]

Dersom det oppdages mindre feil i standarden (stavefeil, upresis formulering etc.), vil ikke
korrigering av disse utløse en ny versjon. Disse korrigeringene skal imidlertid dokumenteres.

Utarbeidelse av nye versjoner av denne standarden initieres av Digitaliseringsdirektoratet. Den primære kilden til nye versjoner vil være endringer i EU-standarden https://semiceu.github.io/DCAT-AP/releases/3.0.0/[DCAT-AP &#x29C9;, window="_blank", role="ext-link"] og W3C-standarden https://www.w3.org/TR/vocab-dcat-3/[DCAT &#x29C9;, window="_blank", role="ext-link"] som denne standarden baseres på. Digitaliseringsdirektoratet vil derfor ha ansvar for å følge med på utviklingen av DCAT-AP og DCAT. 

Digitaliseringsdirektoratet vil i forbindelse med nye versjoner av EU-standarden og/eller W3C-standarden avgjøre om endringene er så store at det bør nedsettes en egen arbeidsgruppe bestående av relevante aktører, eller om revisjonen kan utføres av Digitaliseringsdirektoratet selv. Forslaget til ny versjon sendes uansett på høring. De innkomne høringskommentarene behandles hos Digitaliseringsdirektoratet, og resulterer i et forslag som oversendes https://www.digdir.no/standarder/arkitektur-og-standardiseringsradet/3918[Arkitektur- og standardiseringsrådet &#x29C9;, window="_blank", role="ext-link"].

Gjeldende og eventuelle tidligere versjoner av standarden skal være tilgjengelige på Digitaliseringsdirektoratets nettsider, slik at det er enkelt å finne ut når tidligere versjoner var gyldige, og hvilke endringer som er foretatt mellom to versjoner.
