= Standard for beskrivelse av datasett, datatjenester og datakataloger (DCAT-AP-NO)
Digitalseringsdirektoratet - Arbeidsdokument  - Versjon 2.0
:doctype: book
:docinfo:
:icons: font
:toc: left
:toc-title: Innholdsfortegnelse
:toclevels: 4
:sectlinks:
:table-stripes: even
:leveloffset: +1

Status: Under arbeid +
Publisert: (ikke publisert) +
Lenke til gjeldende versjon: https://data.norge.no/specification/dcat-ap-no +

Dette er et arbeidsdokument for den kommende versjon 2.0 av “Standard for beskrivelse av datasett, datatjenester og datakataloger (DCAT-AP-NO)”. Standarder skal sikre at beskrivelser av offentlige data utføres på en felles, strukturert måte og i en maskinlesbar form. Standarden stiller krav til hva som _skal_, _bør_ og _kan_ være med i beskrivelsene, med spesifikasjon av dataformat.

NOTE: *Innmelding av feil og mangler:* +
Dersom du finner feil eller mangler i dokumentet, ber vi om at dette meldes inn på https://github.com/difi/dcat-ap-no/issues[Github Issues]. Dersom man ikke allerede har bruker på Github kan man opprette bruker gratis. +

include::locale/attributes.adoc[]

include::01_Introduksjon.adoc[]

include::03_Omfang_og_avgrensing.adoc[]

include::04_Forvaltningsregime.adoc[]

include::04b_Om_kravene.adoc[]

include::05_Ord_uttrykk_forkortelser.adoc[]

include::07_Oversikt_over_URIer.adoc[]

include::06_Oversikt_over_klasser.adoc[]

include::07b_diagram.adoc[]

= Egenskaper pr. klasse

:leveloffset: +1

include::08_Katalog.adoc[]

include::09_Katalogpost.adoc[]

include::10_Datatjeneste.adoc[]

include::11_Datasett.adoc[]

include::12_Distribusjon.adoc[]

include::13_Aktor.adoc[]

include::14_Kategoriskjema.adoc[]

include::15_Kategori.adoc[]

include::16_Sjekksum.adoc[]

include::17_Identifikator.adoc[]

include::18_Lisensdokument.adoc[]

include::19_Lokasjon.adoc[]

include::20_Tidsrom.adoc[]

include::21_Relasjoner.adoc[]

:leveloffset: -1

include::22_Kontrollerte_vokabular.adoc[]

include::XX_endringslogg.adoc[]
