= Krav til samsvar [[Samsvarskrav]]

== Krav til applikasjoner som leverer metadata

For å være i samsvar med denne standarden, SKAL en applikasjon som levere metadata:

* Levere en beskrivelse av katalogen, som minimum med de obligatoriske egenskapene spesifisert for <<Katalog>>. 

* Levere informasjon for obligatoriske egenskaper for <<Katalogpost>>, hvis informasjonen finnes, vel å merke at bruken av <<Katalogpost>> er frivillig.  

* Levere beskrivelser av datasettene som er i katalogen, som minimum med de obligatoriske egenskapene spesifisert for <<Datasett>>. 

* Levere beskrivelser av distribusjoner, hvis noen, av datasett i katalogen, som minimum med de obligatoriske egenskapene spesifisert for <<Distribusjon>>. 

* Levere beskrivelser av datatjenester, hvis noen, av datasett i katalogen, som minimum med de obligatoriske egenskapene spesifisert for <<Datatjeneste>>. 

* Levere informasjon om alle organisasjoner/aktører som er involvert i beskrivelsene av katalogen, datasettene osv., som minimum med de obligatoriske egenskapene spesifisert for <<Aktør>>. 

* Bruke de kontrollerte vokabularene som er beskrevet i Merknad til den enkelte egenskapen. Andre kontrollerte vokabularer KAN brukes i tillegg.

== Krav til applikasjoner som mottar metadata

For å være i samsvar med denne standarden, SKAL en applikasjon som mottar metadata:

* Prosessere informasjon for alle klasser og egenskaper som er spesifisert i denne standarden.  

* Prosessere informasjon for alle kontrollerte vokabularer som er eksplisitt spesifisert for de enkelte egenskapene. 


I konteksten datadeling og datautveksling, betyr det «å prosessere» at den mottakende applikasjon aksepterer innkommende data og transparent videreformidler dataene til aktuelle applikasjoner og tjenester. 
