== Om bruk av egenskapene _lisens (dct:license)_, _tilgangsrettigheter (dct:accessRights)_, _rettigheter/brukervilkår (dct:rights)_ og _policy (odrl:hasPolicy)_ [[Om-lisens-tilgang-rettigheter-policy]]

DCAT-AP-NO støtter følgende tre hovedscenarier der man trenger å beskrive tilgang og/eller brukervilkår til en ressurs (f.eks. et datasett): 1) behov for å referere til en lisens, 2) behov for å spesifisere tilgangsrettigheter og 3) andre behov enn ovennevnte, for å uttrykke rettigheter eller brukervilkår, f.eks. opphavsrett. 

DCAT-AP-NO støtter disse scenariene på følgende måte: 

. `dct:license` SKAL brukes til å referere til en lisens, og verdien SKAL hentes fra EUs kontrollerte vokabular https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/licence[__Licence__ &#x29C9;, window="_blank", role="ext-link"]. Dette gjelder egenskapene <<Datatjeneste-lisens>>, <<Distribusjon-lisens>> og <<Katalog-lisens>>. 

. `dct:accessRights` SKAL brukes til å uttrykke tilgangsrettigheter, og verdien SKAL være `PUBLIC`, `RESTRICTED` eller `NON_PUBLIC` fra EU's kontrollerte vokabular https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/access-right[__Access right__ &#x29C9;, window="_blank", role="ext-link"]. Dette gjelder egenskapene <<Datasett-tilgangsrettigheter>> og <<Datatjeneste-tilgangsrettigheter>>. Se også forklaring på disse tre tilgangsnivåene i https://www.digdir.no/informasjonsforvaltning/steg-4-vurdere-tilgangsniva/2723[Steg 4 i Veileder for orden i eget hus &#x29C9;, window="_blank", role="ext-link"], der allmenn tilgang («grønn») svaret til `PUBLIC`, betinget tilgang («gul») svarer til `RESTRICTED` og ikke-allmenn tilgang («rød») svarer til `NON_PUBLIC`.

. `dct:rights` KAN brukes til å uttrykke alle andre typer rettigheter og brukervilkår, bl.a. opphavsrett. Det er anbefalt å bruke <<Rettighetserklæring>> til å ha en strukturert beskrivelse av rettigheter og brukervilkår. Dette gjelder egenskapene <<Distribusjon-rettigheter>> og <<Katalog-rettigheter>>.

W3C/DCAT anbefaler bruk av https://www.w3.org/TR/odrl-vocab/[ODRL (Open Digital Rights Language) &#x29C9;, window="_blank", role="ext-link"] til å spesifisere spesielle bruksvilkår/-regler, som kan refereres til ved å bruke egenskapen  <<Distribusjon-policy>>. Se https://www.w3.org/TR/vocab-dcat-3/#ex-odrl-policy[dette eksemplet i W3C/DCAT &#x29C9;, window="_blank", role="ext-link"], som illustrerer bruken av __ODRL policy__ til å uttrykke hva som er tillatt og ikke tillatt. 