= Vedlegg C - Endringslogg [[Endringslogg]]

Mindre redaksjonelle justeringer av tekster (f.eks. egenskapsnavn, egenskapsbeskrivelser, lenker osv.) beskrives ikke her.

== Endringer av dokumentstrukturen fra versjon 2.2 til denne versjonen 

:xrefstyle: short

Standarden inneholder nå tre hoveddeler i tillegg til det innledende kapittelet og vedleggene:

* <<Forenklet-fremstilling>>  inneholder en forenklet fremstilling av de viktigste kravene i standarden. Denne delen er primært ment for den ikke-tekniske målgruppen. 

* <<Spesifikasjon-per-klasse>>  inneholder tekniske krav til hvordan beskrivelser av datasett, datatjenester osv. skal representeres i RDF. Denne delen er primært ment for den tekniske målgruppen.  
** Hver klasse og dens egenskaper er samlet i samme kapittel, istedenfor to separate kapitler i forrige versjon.
** Krav til bruk av kontrollerte vokabularer er nå tatt med som merknader til de aktuelle egenskapene, istedenfor i eget kapittel i forrige versjon. 
** Eventuelle norske utvidelser sammenlignet med DCAT-AP og DCAT, er dokumentert sammen med spesifikasjonen av den aktuelle klassen/egenskapen, i tillegg til en samlet oversikt i <<Oversikt-norske-utvidelser>>. 

** Tabeller som brukes til å spesifisere klasser og egenskaper er endret:

*** Tabellene har fått nye ledetekster.
*** Det er nå også tatt med engelsk tekst, primært ment for engelsktalende utviklere av verktøystøtte. 

* <<Spesielle-temaer>> inneholder forklaring/veiledning til hvordan DCAT-AP-NO er tenkt brukt i noen spesifikke brukstilfeller. Denne delen er ment for både den ikke-tekniske og den tekniske målgruppen, fortrinnsvis sammen. Denne delen sammen med eksemplene gitt i standarden, skal (over tid) erstatte en separat veileder for hvordan standarden er tenkt brukt. 

:xrefstyle: full

== Endringer av klasser og egenskaper fra versjon 2.2 til denne versjonen

=== Overordnede endringer

Revisjon fra versjon 2.2 til denne versjon 3.0 av DCAT-AP-NO er trigget av EUs utgivelse av DCAT-AP hovedversjon 3.0. Hensikten med revisjonen er å gjøre DCAT-AP-NO mest mulig i samsvar med den nye versjonen av DCAT-AP. EU har begynt å ikke gjenta valgfrie egenskaper fra W3Cs DCAT når det ikke gjøres tilpasninger i DCAT-AP. Dette medfører at DCAT-AP må brukes sammen med DCAT. Denne versjonen av DCAT-AP-NO er derfor basert på summen av DCAT-AP og DCAT (istedenfor BRegDCAT-AP som forrige versjon var basert på og som den gang inneholdt hele DCAT-AP med utvidelser). Norske utvidelser/avvik er derfor også i forhold til summen av DCAT-AP og DCAT. 

Denne versjonen spesifiserer _ikke_ kravnivå (obligatorisk/anbefalt/valgfri) for klassene, se imidlertid <<Samsvarskrav>> for hva applikasjonene skal kunne håndtere. Dette i henhold til EUs DCAT-AP. 

I henhold til DCAT-AP som følger DCAT når det gjelder inverse egenskaper, er inverse egenskaper ikke tatt med i standarden. Alle inverse egenskaper er derfor utgått fra denne versjonen av DCAT-AP-NO. Man __kan__ bruke en invers egenskap, _i tillegg til_ og _ikke istedenfor_ egenskapen som er eksplisitt tatt med i standarden. Se <<Om-inverse-egenskaper>>.

=== Nye klasser

Følgende er klasser som er enten helt nye eller eksplisitt spesifisert med egenskaper i denne versjonen: 

* <<Gebyr>>, for å kunne beskrive ev. kostnader knyttet til bruk av et datasett, med standardiserte egenskaper.
* <<Kontaktopplysning>>, for å kunne beskrive et kontaktpunkt, med standardiserte egenskaper.
* <<Rettighetserklæring>>, for å kunne beskrive ev. rettigheter knyttet til et datasett osv., med standardiserte egenskaper.

=== Utgåtte klasser

Følgende er klasser som i denne versjonen ikke lenger er eksplisitt spesifisert med egenskaper, og som derfor ikke tas med i denne versjonen: 

* Lisensdokument (`dct:LicenseDocument`): Det ikke er behov for å lage egne instanser av denne klasse fordi egenskapene som bruker denne klassen som verdiområde skal referere til kontrollerte vokabularer.
* Lokasjon (`dct:Location`): Det ikke er behov for å lage egne instanser av denne klasse fordi egenskapene som bruker denne klassen som verdiområde skal referere til kontrollerte vokabularer.
* Offentlig organisasjon (`cv:PublicOrganisation`): Behovet er dekket av https://data.norge.no/specification/cpsv-ap-no[CPSV-AP-NO &#x29C9;, window="_blank", role="ext-link"]. 
* Offentlig tjeneste (`cpsv:PublicService`): Behovet er dekket av https://data.norge.no/specification/cpsv-ap-no[CPSV-AP-NO &#x29C9;, window="_blank", role="ext-link"].
* Regel (`cpsv:Rule`): Behovet er dekket av https://data.norge.no/specification/cpsv-ap-no[CPSV-AP-NO &#x29C9;, window="_blank", role="ext-link"].
* Tema (`skos:Concept`): Det ikke er behov for å lage egne instanser av denne klasse fordi egenskapene som bruker denne klassen som verdiområde skal referere til kontrollerte vokabularer.
* Tematisk skjema (`skos:ConceptScheme`): Det ikke er behov for å lage egne instanser av denne klasse fordi egenskapene som bruker denne klassen som verdiområde skal referere til kontrollerte vokabularer.

=== Endrede krav i eksisterende klasser

* <<Datasett>>: 
** *Nye egenskaper*:
*** <<Datasett-gjeldendeLovgivning>>, i samsvar med DCAT-AP/DCAT.
*** <<Datasett-har-gebyr>>, for å kunne oppgi ev. kostnader knyttet til bruk av datasettet.
*** <<Datasett-tilgangsForespørselsURL>>, for å kunne dekke behov for å oppgi siden eller tjenesten som håndterer tilgangsforespørsel. 

** *Utgåtte egenskaper*: 
*** er del av (`dct:isPartOf`), i samsvar med DCAT-AP/DCAT. Se også <<Om-inverse-egenskaper>>.
*** er påkrevd av (`dct:isRequiredBy`), i samsvar med DCAT-AP/DCAT.
*** er versjon av (`dct:isVersionOf`), i samsvar med DCAT-AP/DCAT. Se også <<Om-inverse-egenskaper>>.
*** erstattes av (`dct:isReplacedBy`), i samsvar med DCAT-AP/DCAT. Se også <<Om-inverse-egenskaper>>.
*** følger (`cpsv:follows`), i samsvar med DCAT-AP/DCAT. 
*** har del (`dct:hasPart`), i samsvar med DCAT-AP/DCAT. Behovet er dessuten dekket av Datasettserie. 
*** krever (`dct:requires`), i samsvar med DCAT-AP/DCAT. 
*** refererer til (`dct:references`), i samsvar med DCAT-AP/DCAT. Se også <<Om-inverse-egenskaper>>.

** *Endrede egenskapsURIer*: 
*** <<Datasett-versjon>>: EgenskapsURIen er endret fra `owl:versionInfo` til `dcat:version`, i samsvar med DCAT-AP/DCAT.

** *Endrede kravnivå og/eller multiplisitet*: 
*** <<Datasett-beskrivelse>>: Føyet til følgende krav: Det SKAL være maks. 1 verdi per språk.
*** <<Datasett-kontaktpunkt>>: Kravnivået er endret fra anbefalt til obligatorisk og dermed også multiplisiteten fra 0..n til 1..n, i samsvar med DCAT-AP/DCAT.
*** <<Datasett-tittel>>: Føyet til følgende krav: Det SKAL være maks. 1 verdi per språk.
*** <<Datasett-identifikator>>: Kravnivået er endret fra obligatorisk til valgfri, i samsvar med DCAT-AP/DCAT. 
*** <<Datasett-romligOppløsning>>: Multiplisiteten er endret fra 0..n til 0..1, i samsvar med DCAT-AP/DCAT. 
*** <<Datasett-produsent>>: Multiplisiteten er endret fra 0..1 til 0..n, i samsvar med DCAT-AP/DCAT. 
*** <<Datasett-tidsoppløsning>>: Multiplisiteten er endret fra 0..n til 0..1, i samsvar med DCAT-AP/DCAT. 
*** <<Datasett-type>>: Multiplisiteten er endret fra 0..1 til 0..n, i samsvar med DCAT-AP/DCAT. 

** *Endrede verdiområder*: 
*** <<Datasett-beskrivelse>>: Verdiområdet endret fra rdfs:Literal til rdf:langString som er en subklasse av rdfs:Literal. 
*** <<Datasett-tittel>>: Verdiområdet endret fra rdfs:Literal til rdf:langString som er en subklasse av rdfs:Literal. 
*** <<Datasett-emneord>>: Verdiområdet endret fra rdfs:Literal til rdf:langString som er en subklasse av rdfs:Literal. 
*** <<Datasett-versjonsmerknad>>: Verdiområdet endret fra rdfs:Literal til rdf:langString som er en subklasse av rdfs:Literal. 

** *Endrede krav til bruk av kontrollerte vokabularer*: 
*** <<Datasett-bleGenerertVed>>: Nytt krav til bruk av kontrollerte vokabular «Proveniensaktivitetstype». Dette for å kunne ha standardiserte verdier av denne egenskapen. 
*** <<Datasett-produsent>>: Det er ikke lenger krav til bruk av kontrollerte vokabularer, i samsvar med DCAT-AP/DCAT.
*** <<Datasett-tema>>: EuroVoc er utgått fra kravet til bruk av kontrollerte vokabularer, i samsvar med DCAT-AP/DCAT.

* <<Datasettserie>>: 
** *Nye egenskaper*:
*** <<Datasettserie-beskrivelse>>, i samsvar med DCAT-AP/DCAT.. 
*** <<Datasettserie-endringsdato>>, i samsvar med DCAT-AP/DCAT. 
*** <<Datasettserie-frekvens>>, i samsvar med DCAT-AP/DCAT. 
*** <<Datasettserie-gjeldendeLovgivning>>, i samsvar med DCAT-AP/DCAT.
*** <<Datasettserie-kontaktpunkt>>, i samsvar med DCAT-AP/DCAT. 
*** <<Datasettserie-tema>>, i samsvar med DCAT-AP/DCAT. 
*** <<Datasettserie-tittel>>, i samsvar med DCAT-AP/DCAT. 
*** <<Datasettserie-utgivelsesdato>>, i samsvar med DCAT-AP/DCAT. 
*** <<Datasettserie-utgiver>>, i samsvar med DCAT-AP/DCAT. 
*** <<Datasettserie-tidsrom>>, i samsvar med DCAT-AP/DCAT.

** *Utgåtte egenskaper*: 
*** følger (`cpsv:follows`), i samsvar med DCAT-AP/DCAT.

** *Endrede kravnivå og/eller multiplisitet*: 
*** <<Datasettserie-første>>: Kravnivået endret fra obligatorisk til valgfri og dermed også multiplisiteten fra 1..1 til 0..1, i samsvar med DCAT-AP/DCAT. Dette fordi ikke alle datasettserier er ordnede. 


* <<Datatjeneste>>: 
** *Nye egenskaper*:
*** <<Datatjeneste-gjeldendeLovgivning>>, i samsvar med DCAT-AP/DCAT.
*** <<Datatjeneste-status>>, for å kunne dekke behov for å angi status.
*** <<Datatjeneste-tilgangsForespørselsURL>>, for å kunne dekke behov for å oppgi siden eller tjenesten som håndterer tilgangsforespørsel. 
*** <<Datatjeneste-versjon>>, i samsvar med DCAT-AP/DCAT.
*** <<Datatjeneste-versjonsmerknad>>, i samsvar med DCAT-AP/DCAT.

** *Utgåtte egenskaper*:
*** medietype (dcat:mediaType), i samsvar med DCAT-AP/DCAT.
*** type (dct:type), ikke i bruk i dag, uklar bruksområder. 

** *Endrede kravnivå og/eller multiplisitet*: 
*** <<Datatjeneste-kontaktpunkt>>: Kravnivået er endret fra anbefalt til obligatorisk og dermed også multiplisiteten fra 0..n til 1..n. Dette for å kunne ta kontakt med den ansvarlige.
*** <<Datatjeneste-identifikator>>: Kravnivået er endret fra obligatorisk til valgfri, i samsvar med DCAT-AP/DCAT.
*** <<Datatjeneste-i-samsvar-med>>: Kravnivået er endret fra valgfri til anbefalt, i samsvar med DCAT-AP/DCAT.
*** <<Datatjeneste-utgiver>>: Kravnivået endret fra anbefalt til obligatorisk og dermed også multiplisiteten fra 0..1 til 1..1. Dette for å kunne gruppere datatjenester/APIer under virksomhet i GUIen i data.norge.no. 

** *Endrede krav til bruk av kontrollerte vokabularer*: 
*** <<Datatjeneste-tema>>: "EuroVoc" er utgått fra kravet til bruk av kontrollerte vokabularer, i samsvar med DCAT-AP/DCAT. 

* <<Distribusjon>>: 
** *Nye egenskaper*:
*** <<Distribusjon-gjeldendeLovgivning>>, i samsvar med DCAT-AP/DCAT.

** *Endrede kravnivå og/eller multiplisitet*: 
*** <<Distribusjon-medietype>>: Multiplisiteten endret fra 0..n til 0..1, i samsvar med DCAT-AP/DCAT.
*** <<Distribusjon-romlig-oppløsning>>: Multiplisiteten endret fra 0..n til 0..1, i samsvar med DCAT-AP/DCAT.
*** <<Distribusjon-tidsoppløsning>>: Multiplisiteten endret fra 0..n til 0..1, i samsvar med DCAT-AP/DCAT.
*** <<Distribusjon-format>>: Multiplisiteten endret fra 0..n til 0..1, i samsvar med DCAT-AP/DCAT.

** *Endrede krav til bruk av kontrollerte vokabularer*: 
*** <<Distribusjon-komprimeringsformat>>: Tilføyet kravet til å bruke kontrollert vokabular "File type",for å ha standardiserte verdier for denne egenskapen. 
*** <<Distribusjon-pakkeformat>>: Tilføyet kravet til å bruke kontrollert vokabular "File type", for å ha standardiserte verdier for denne egenskapen.  
*** <<Distribusjon-status>>: "ADMS status vocabulary" er erstattet med EUs kontrollerte vokabular for "Distribution status", i samsvar med DCAT-AP/DCAT.  


* <<Katalog>>: 
** *Nye egenskaper*:
*** <<Katalog-kontaktpunkt>>, i samsvar med DCAT-AP/DCAT.
*** <<Katalog-gjeldendeLovgivning>>, i samsvar med DCAT-AP/DCAT.
*** <<Katalog-tidsrom>>, i samsvar med DCAT-AP/DCAT.

** *Utgåtte egenskaper*: 
*** er del av (`dct:isPartOf`), i samsvar med DCAT-AP/DCAT. Se også <<Om-inverse-egenskaper>>.
*** frekvens (`dct:accrualPeriodicity`), i samsvar med DCAT-AP/DCAT.
*** opphav (`dct:provenance`), i samsvar med DCAT-AP/DCAT.

** *Endrede kravnivå og/eller multiplisitet*: 
*** <<Katalog-identifikator>>: Kravnivået endret fra obligatorisk til valgfri og dermed også multiplisiteten fra 1..1 til 0..1, i samsvar med DCAT-AP/DCAT.

** *Endrede krav til bruk av kontrollerte vokabularer*: 
*** <<Katalog-produsent>>: Kravet om bruk av EUs kontrollerte vokabular "Corporate body" utgått, i samsvar med DCAT-AP/DCAT.
*** <<Katalog-temaer>>: "EuroVoc" utgått og "Data theme" tilføyet i kravet om bruk av kontrollerte vokabularer, i samsvar med DCAT-AP/DCAT. 

* <<Katalogpost>>: 
** *Endrede kravnivå og/eller multiplisitet*: 
*** <<Katalogpost-i-samsvar-med>>: Multiplisiteten endret fra 0..1 til 0..n, i samsvar med DCAT-AP/DCAT.
** *Endrede krav til bruk av kontrollerte vokabularer*: 
*** <<Katalogpost-status>>: "ADMS status vocabulary" er erstattet av EUs kontrollerte vokabular for "Distribution status". Dette for å samkjøre med tilsvarende egenskaper i de andre klassene. 

* <<RegulativRessurs>>: 
** *Nye egenskaper*:
*** <<RegulativRessurs-språk>>, for å kunne oppgi språk. 
***  <<RegulativRessurs-tittel>>, for å kunne oppgi tittel. 
** *Endrede kravnivå og/eller multiplisitet*: 
*** <<RegulativRessurs-identifikator>>: Multiplisiteten endret fra 0..n til 0..1. Denne type ressurser bør ha maks. én identifikator. Dette også for å samkjøre med https://data.norge.no/specification/cpsv-ap-no[CPSV-AP-NO &#x29C9;, window="_blank", role="ext-link"]. 
*** <<RegulativRessurs-type>>: Kravnivået endret fra obligatorisk til anbefalt, og multiplisiteten fra 0..n til 0..1 (denne type ressurser bør være av maks. én type). Dette for å samkjøre med https://data.norge.no/specification/cpsv-ap-no[CPSV-AP-NO &#x29C9;, window="_blank", role="ext-link"].

* <<Sjekksum>>: 
** *Endrede krav til bruk av kontrollerte vokabularer*: 
*** <<Sjekksum-algoritme>>: Føyet til krav om å velge en av de forhåndsdefinerte algoritmene, istedenfor å referere til én og bare én gitt algoritme som verdiområde/range, i samsvar med DCAT-AP/DCAT. 

* <<Standard>> 
** *Endrede egenskapsURIer*:
*** <<Standard-harVersjonsnummer>>: EgenskapsURIen endret fra `owl:versionInfo` til `dcat:version`. Dette for å samkjøre med tilsvarende egenskaper i de andre klassene. 
