name: build adocs

permissions:
  contents: write

on:
  push:
    branches:
      - v2
    paths:
      - docs/**

jobs:
  build-adocs:
    uses: Informasjonsforvaltning/workflows/.github/workflows/specification-github-pages.yaml@main
    with:
      program_html: |
        asciidoctor -D docs -o index.html -a lang=nb docs/main.adoc
      program_pdf: |
        asciidoctor-pdf -D docs -o files/dcat-ap-no.pdf -a lang=nb docs/main.adoc
      publish_branch: html
      publish_dir: ./docs
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}