name: (ad hoc) Publish ontology from develop to data.norge.no/vocabulary

on:
  push:
    branches:
      - develop
    paths:
      - ontology/**
  workflow_dispatch:

jobs:
  test_uploading_of_file:
    name: Upload vocabulary to static-rdf-server
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload files to static-rdf-server
        uses: Informasjonsforvaltning/upload-files-to-static-rdf-server-action@v3.2.0
        id: upload-files
        with:
          ontology-type: "vocabulary"
          ontology: "dcatno"
          host: "https://data.norge.no"
          api-key: ${{ secrets.STATIC_RDF_SERVER_API_KEY }}
          files: |
            ontology/dcatno.ttl text/turtle en
            ontology/index.html text/html nb
