name: Publish ontology to data.norge.no/vocabulary

permissions:
  contents: read

on:
  push:
    branches:
      - v3
    paths:
      - ontology/**
  workflow_dispatch:

jobs:
  upload-files-to-production:
    name: Upload vocabulary to static-rdf-server
    uses: Informasjonsforvaltning/workflows/.github/workflows/specification-upload-files.yaml@main
    with:
      ref: v3
      program_html: |
        asciidoctor -a data-uri -D ontology -o index-en.html -a lang=en ontology/main-en.adoc
        asciidoctor -a data-uri -D ontology -o index-nb.html -a lang=nb ontology/main-nb.adoc
      files: |
        ontology/dcatno.ttl text/turtle en
        ontology/index-nb.html text/html nb
        ontology/index-en.html text/html en
      host: https://data.norge.no
      ontology: dcatno
      ontology-type: vocabulary
    secrets:
      STATIC_RDF_SERVER_API_KEY: ${{ secrets.STATIC_RDF_SERVER_API_KEY }}
