name: build adocs and publish v2 to production (.../v.2.2)

on:
  push:
    branches:
      - v2
    paths:
      - docs/**
  workflow_dispatch:

jobs:
  adoc_build:
    runs-on: ubuntu-latest
    name: asciidoctor build

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: v2
          submodules: true
          fetch-depth: 0

      - name: Update submodules to latest main
        run: |
          git submodule foreach --recursive git fetch origin
          git submodule foreach --recursive git checkout origin/main

      - name: Build html
        id: adocbuild
        uses: tonynv/asciidoctor-action@master
        with:
          program: "asciidoctor -D docs -o index.html -a lang=nb docs/main.adoc"

      - name: Upload rdf to static-rdf-server
        uses: Informasjonsforvaltning/upload-files-to-static-rdf-server-action@v3.2.0
        id: upload-rdf
        with:
          ontology-type: "specification"
          ontology: "dcat-ap-no"
          version: "v2.2"
          host: "https://data.norge.no"
          api-key: ${{ secrets.STATIC_RDF_SERVER_API_KEY }}
          files: |
            docs/index.html text/html nb
            docs/files/DCAT-AP-NO2_20210903.eap application/octet-stream nb files/DCAT-AP-NO2_20210903.eap
            docs/images/digitaliseringsdirektoratet.png image/png nb images/digitaliseringsdirektoratet.png
            docs/images/DCAT-AP-NO2_20210903.png image/png nb images/DCAT-AP-NO2_20210903.png
