name: build adocs and publish v1.1 to production

permissions:
  contents: read

on:
  push:
    branches:
      - v1.1
    paths:
      - docs/**
  workflow_dispatch:

jobs:
  upload-files-to-production:
    name: Upload specification to static-rdf-server
    uses: Informasjonsforvaltning/workflows/.github/workflows/specification-upload-files.yaml@main
    with:
      ref: v1.1
      program_html: |
        asciidoctor -D docs -o index.html -a lang=nb docs/main.adoc
      program_pdf: |
        asciidoctor-pdf -D docs -o files/dcat-ap-no.pdf -a lang=nb docs/main.adoc
      files: |
        docs/index.html text/html nb
        docs/files/dcat-ap-no.pdf application/pdf nb files/dcat-ap-no.pdf
        docs/files/dcat-ap-no-1.1p2.uxf text/xml nb files/dcat-ap-no-1.1p2.uxf
        docs/files/dcat-ap-no-1.1p3.png image/png nb files/dcat-ap-no-1.1p3.png
        docs/images/dcat-ap-no-1-1-diagram.png image/png nb images/dcat-ap-no-1-1-diagram.png
        docs/images/dcat-ap-no-1.1p3.png image/png nb images/dcat-ap-no-1.1p3.png
      host: https://fellesdatakatalog.digdir.no
      ontology: dcat-ap-no
      ontology-type: specification
      version: v1.1
    secrets:
      STATIC_RDF_SERVER_API_KEY: ${{ secrets.STATIC_RDF_SERVER_API_KEY }}
