name: build adocs and publish v2 to production (.../v.2.2)

permissions:
  contents: read

on:
  push:
    branches:
      - v2
    paths:
      - docs/**
  workflow_dispatch:

jobs:
  upload-files-to-production:
    name: Upload specification to static-rdf-server
    uses: Informasjonsforvaltning/workflows/.github/workflows/specification-upload-files.yaml@main
    with:
      ref: v2
      program_html: |
        asciidoctor -D docs -o index.html -a lang=nb docs/main.adoc
      files: |
        docs/index.html text/html nb
        docs/files/DCAT-AP-NO2_20210903.eap application/octet-stream nb files/DCAT-AP-NO2_20210903.eap
        docs/images/digitaliseringsdirektoratet.png image/png nb images/digitaliseringsdirektoratet.png
        docs/images/DCAT-AP-NO2_20210903.png image/png nb images/DCAT-AP-NO2_20210903.png
      host: https://data.norge.no
      ontology: dcat-ap-no
      ontology-type: specification
      version: v2.2
    secrets:
      STATIC_RDF_SERVER_API_KEY: ${{ secrets.STATIC_RDF_SERVER_API_KEY }}